### ISSUE TITLE
Playbox Fullwidth + Cover

### ISSUE THREAD

**Issue by eramdam** [felixhageloh/uebersicht-widgets#114]
Hi! I made a fork of Playbox, it got a fullwidth style + a cover

https://github.com/eramdam/Playbox-full-cover

![screenshot](https://cloud.githubusercontent.com/assets/1409924/5404497/6e5e2e56-8197-11e4-98c4-ef14ec773077.png)

**Comment by felixhageloh** [comment]
I'll close this issue for now
