### ISSUE TITLE
calendar - not translated though cal is

### ISSUE THREAD

**Issue by TraderStf** [felixhageloh/uebersicht-widgets#115]
Hello,

Calendar is not translated though if I type just 'cal' in terminal, it is displayed in French.

I have hard coded the day "Lu Ma...Di" so this one is ok.
The month remains in English.

ncal has a country id not cal.

Any idea where I can search to solve this.

Thank you very much.

**Comment by felixhageloh** [comment]
not quite sure - maybe there is some parsing of the output happening in the widget and english names are used

**Comment by felixhageloh** [comment]
Did you find a way to solve this?

**Comment by TraderStf** [comment]
No nothing, no parameter, no setting... did not find any clue. I hard code it and if = then

**Comment by cytec** [comment]
same goes for the date command btw...
seem like übersicht sets a locale or something?

**Comment by felixhageloh** [comment]
coming back to this old issue: Übersicht does not set a locale but it uses a non-login shell so it does not keep `.profile` or `.bashrc` settings. This means it uses the default locale of English. you can fix it by setting your locale manually like so:

```coffeescript
command: "export LC_ALL=it_IT.UTF-8; cal"
```

I think the next release of Übertsicht will use a login shell, so all your settings should work automatically.
