### ISSUE TITLE
Mac Calendar Widget

### ISSUE THREAD

**Issue by djbrooks111** [felixhageloh/uebersicht-widgets#120]
I made this widget that displays the Calendar events for today and tomorrow.

You can find it here:
https://github.com/djbrooks111/ical-widget

Thanks

**Comment by soberstadt** [comment]
Any chance you could add a plain-text version of that iCalBuddy script?

**Comment by djbrooks111** [comment]
I didn't make the icalBuddy script, you can find it here: http://hasseg.org/icalBuddy/

The issue is that Apple doesn't really expose the Calendar events and that is where icalBuddy comes into play.  It was originally made for GeekTool, but since Ubersicht can run a command, I thought that it would be just fine running the icalBuddy script.

**Comment by soberstadt** [comment]
Ah, I see. That makes sense. Another Apple product without an api :)




Could you add a link to that page/repo either in the widget description or a README file. 




This is a great idea!

**Comment by djbrooks111** [comment]
Okay, I added the link to both the description in the manifest, the description in my code and in a Readme :)

**Comment by djbrooks111** [comment]
I don't know if you did anything with my widget yet, but I just updated it to print "No Events Today or Tomorrow" if you have not scheduled calendar events.  Therefore, at least the user sees some indication that the widget is still working and not just blank space on their desktop

**Comment by soberstadt** [comment]
The widget is added, you should see it on the gallery now. So you know, as you update your repo, changes will automatically be available on the gallery, the link points right at the zip file.
