### ISSUE TITLE
spaceAPI widget

### ISSUE THREAD

**Issue by Kaweechelchen** [felixhageloh/uebersicht-widgets#121]
Hey, can you add https://github.com/Kaweechelchen/spaceAPI-widget pls?
thx

**Comment by soberstadt** [comment]
thanks, it has been added! You might want to check the screenshot - it has the wrong proportions so it gets a a bit squashed on the website (you can find the recommended sizes in the [readme](https://github.com/felixhageloh/uebersicht-widgets/blob/master/README.md#screenshot))

**Comment by Kaweechelchen** [comment]
done ;) https://github.com/Kaweechelchen/spaceAPI-widget/commit/9ea1f6a3363030a6e7cb45aa83fe108dcdb483ed
sry, didn't read the details of the readme :D
