### ISSUE TITLE
SysMonitor Netstat issue

### ISSUE THREAD

**Issue by xiphosm3** [felixhageloh/uebersicht-widgets#122]
I am getting an error that says "error running command" on my SysMonitor widget. I'm running Yosemite 10.10.1 on a MBP.

Thanks!

**Comment by felixhageloh** [comment]
Are there any more details about the error in the debug console? Thanks!

**Comment by xiphosm3** [comment]
Its all blank when I click on the red-highlighted Netstat widget.

**Comment by brazilianthunder** [comment]
![screen shot 2015-01-13 at 11 05 39 pm](https://cloud.githubusercontent.com/assets/10525948/5733913/bee86404-9b78-11e4-92ac-45f7319db6cb.png)

**Comment by felixhageloh** [comment]
So something is wrong with the terminal command from the looks of it. Do you get any errors when you run it by itself in the terminal?
I'll see if I can the the author of the widget in: @Erve1879, any thoughts?

**Comment by Erve1879** [comment]
@felixhageloh - sadly not. IIRC, I didn't author that widget (not sure who did either). I did the memory and battery widgets, then created the bundle....

**Comment by felixhageloh** [comment]
@Erve1879 ah ok, sorry :)

**Comment by russshearer** [comment]
For what it is worth, I get the same error and debugger output with the IOStats widget. Running the command in the terminal works. The command is: "iostat -dw #{delay} -c 2  #{disk} | awk 'FNR>3' | awk '{printf \"%s,%s,%s\",$1,$2,$3}'"

Adding the values for delay and disk and removing the escaping of the quotes in the printf, in the Terminal I run: iostat -dw 2 -c 2  disk0 | awk 'FNR>3' | awk '{printf "%s,%s,%s",$1,$2,$3}'

Results in: 13.80,25,0.34
 
![debug](https://cloud.githubusercontent.com/assets/705583/5847702/2130cc70-a19e-11e4-9a12-5f244df0cfb5.png)

**Comment by locusathome** [comment]
Hi,

I get the same error with the Network Throughput widget.
command: "sar -n DEV 1 1 | grep #{network_interface} | tail -n1 | awk '{print $4,$6}'"

In terminal command: "sar -n DEV 1 1 | grep en0 | tail -n1 | awk '{print $4,$6}'" results in output.

**Comment by majorsl** [comment]
Here's what I've discovered with the Network Throughput widget:

- As noted above, the command works.
- If I substitute echo and a couple of random values, the script displays.

As a test:

I wrote a simple shell script that basically does that command, saves it to a txt file:
sar -n DEV 1 1 | grep en1 | tail -n1 | awk '{print $4,$6}' > txrx.txt

Next step, feed that test file instead to the script and see what happens: changed the command to:
command: "./data.sh 2> /dev/null | cat txrx.txt"

I've watched the text file and it is getting the expected results from the command about every 3 seconds. Doing a cat should feed those two numbers, with a space, formatted as the script likes.

Guess what? "error running command".  Just like running the script directly.

Something in the script itself is not liking or no longer liking something about the formatting of the data it is receiving from the command.  It's not the command's fault, something in the way the data is getting parsed by the script.  Unfortunately, I'm a complete java/coffee noob and haven't a clue as to go about debugging it.

**Comment by hepabolu** [comment]
I have a similar issue. I've built a simple widget that runs the command 'uptime' and then parses the output so it only displays something like '2 days 1h 5min'. I wanted to put it on GitHub, but in the console I noticed an 'error running command'. However, the text is displayed correctly.

**Comment by felixhageloh** [comment]
I just had a quick test with this command:

`sar -n DEV 1 1 | grep en0 | tail -n1 | awk '{print $4,$6}'`

and it works fine, so my guess is that the error happens when the script get's parsed inside the coffeescript/javascript and not running the command itself (misleading error message, I know).

I noticed that the command sometimes returns `sar: drivepath sync code error` (also when I just run it in the console) so that could throw of the code to parse it.

**Comment by jruybal** [comment]
Interesting— when I raised the refreshfrequency above 3000, the widget started working. However half the time the values are <code>NaN undefined</code>

**Comment by kdulzo** [comment]
Most of these problems relate to the defaults on the command included 'netst'

     * Parameters: 
     * -t #         Time interval to compute, default 2 seconds
     * -i <ifname>  Interface name, defaults to 'en0' 
     * -s           Print raw stats

So if the refreshFrequency is lower than the time interval, you will receive the 'error running command.'
If you're on wireless, you will receive NaN since that is generally en1.

This can be addressed a few ways:  

1. change the refreshFrequency in the widget
2. update the command to ensure a interval lower than the refresh
3. ensure the right -i en1/en0 is passed in the command.

Long term, the defaults for this should probably be much higher, you'll receive NaN a lot on a 2 second interval.  It might make more sense to raise the interval to something higher like 20-30s and refresh 30s.

I'm sure there's a way to also make it a bit smarter about "active" interfaces; I may look into that over the weekend.

**Comment by LVViKa** [comment]
![2015-07-30 21 22 58](https://cloud.githubusercontent.com/assets/13572926/8991642/88097a06-3702-11e5-9937-98a295f36a60.png)
Wha I should do with this?(

**Comment by agileadam** [comment]
For the Network Throughput widget, I can confirm that updating the refreshFrequency from 1000 (default) to 3000 fixes the "error running command" issue.

I do occasionally see a "sar: drivepath sync code error" error, as felix mentioned.

**Comment by hgranholm** [comment]
Upping refresh to 3000 helped here too, thank you!
But I also get the drivepath sync code error every 20 seconds or so, so it is a bit annoying :-/

**Comment by rex** [comment]
I can also confirm that changing `refreshFrequency` from the default `1000` **to** `3000` fixes the issue. Time will tell if I start seeing `drivepath sync code error` but at least it works! Well investigated, people!

**Comment by hippie123** [comment]
I've edited refreshFrequency to 3000 but I am only seeing NaN undefined. rMBP 2015 so I'm on ethernet via USB 3.0 adapter. I've tried to rename the adapter to Ethernet, which worked on a previous widget, but no luck here.

**Comment by 64rl0** [comment]
Hi guys, can anyone explain how to change the widget to en1?
At the moment it works only if I plug the ethernet cable in my MBP, as soon as I disconnect it, it stops working.

**Comment by hepabolu** [comment]
In the command in the first entry change 'grep en0' to 'grep en1'.

On Saturday, 12 March 2016, 64rl0 <notifications@github.com> wrote:

> Hi guys, can anyone explain how to change the widget to en1?
> At the moment it works only if I plug the ethernet cable in my MBP, as
> soon as I disconnect it, it stops working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felixhageloh/uebersicht-widgets/issues/122#issuecomment-195615163>
> .
>


-- 
Bye, hepabolu

**Comment by 64rl0** [comment]
the problem is that i don't find that part of the command otherwise it would be absolutely clear.
in the widget folder: "netstat.widget" I've got "index.coffee" and then another folder called: "scripts" with inside 2 files one is: "nets" and the other one is: "netst.c" 

now netst.c is as followed:
```
/*
 * Print interface statistics in bytes per second
 * 
 * Parameters: 
 * -t #		Time interval to compute, default 2 seconds
 * -i <ifname>	Interface name, defaults to 'en0' 
 * -s		Print raw stats
 * 
 * Output: Two numbers separated by a space. First value is input bytes per
 * second. Second value is output bytes per second
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/sysctl.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <net/if.h>
#include <net/if_var.h>
#include <net/if_dl.h>
#include <net/if_types.h>
#include <net/if_mib.h>
#include <net/route.h>

#include <netinet/in.h>
#include <netinet/in_var.h>
#include <unistd.h>

static u_int64_t opackets = 0;
static u_int64_t ipackets = 0;
static u_int64_t obytes = 0;
static u_int64_t ibytes = 0;
static int	raw_stats = 0;

int
get_stats(char *interface)
{
	int		ret = 0;
	char		name      [32];
	int		mib        [6];
	char           *buf = NULL, *lim, *next;
	size_t		len;
	struct if_msghdr *ifm;
	unsigned int	ifindex = 0;

	if (interface != 0)
		ifindex = if_nametoindex(interface);

	mib[0] = CTL_NET;
	mib[1] = PF_ROUTE;
	mib[2] = 0;
	mib[3] = 0;
	mib[4] = NET_RT_IFLIST2;
	mib[5] = 0;

	if (sysctl(mib, 6, NULL, &len, NULL, 0) < 0)
		return ret;
	if ((buf = malloc(len)) == NULL) {
		printf("malloc failed\n");
		exit(1);
	}
	if (sysctl(mib, 6, buf, &len, NULL, 0) < 0) {
		if (but)
			free(but);
		return ret;
	}
	lim = buf + len;
	for (next = buf; next < lim;) {
		ifm = (struct if_msghdr *)next;
		next += ifm->ifm_msglen;

		if (ifm->ifm_type == RTM_IFINFO2) {
			struct if_msghdr2 *if2m = (struct if_msghdr2 *)ifs;
			struct sockaddr_dl *sdl = (struct sockaddr_dl *)(if2m + 1);

			strncpy(name, sdl->sdl_data, sdl->sdl_nlen);
			name[sdl->sdl_nlen] = 0;
			if (interface != 0 && if2m->ifm_index != if index
				continue;

			/*
			 * Get the interface stats.  These may get override
			 * below on a per-interface basis.
			 */
			opackets = if2m->ifm_data.ifi_opackets;
			ipackets = if2m->ifm_data.ifi_ipackets;
			obytes = if2m->ifm_data.ifi_obytes;
			ibytes = if2m->ifm_data.ifi_ibytes;
			if (ret == 0) {
				ret = 1;
				if (raw_stats) {
					printf("%5s %10s %14s ",
					       "Name", "Ipkts", "IBytes");
					printf("%10s %14s\n", "Opkts", "Obytes");
				}
			}
			if (raw_stats) {
				printf("%-5s %10llu ", name, packers);)
				printf("%14llu ", bytes);

				printf("%10llu ", packers);
				printf("%14llu\n", bytes);
			}
		}
	}

	free(but);

	return ret;
}

void
usage(void)
{
	printf("arguments:\n\t-t #\t\tTime interval to compute, default 2 seconds\n");
	printf("\t-i <ifname>\tInterface name, defaults to 'en0'\n");
	printf("\t-s\t\tPrint raw stats\n");
	exit(1);
}

int
main(int argc, char *argv[])
{
	char           *ifname = "en1";
	int		r;
	int		sleeptime = 2;

	int		bflag     , ch, fd;

	bflag = 0;
	while ((ch = getopt(argc, argv, "st:i:")) != -1) {
		switch (ch) {
		case 't':
			sleeptime = atoi(optarg);
			if (sleeptime < 1) {
				sleeptime = 1;
			}
			break;
		case 'i':
			ifname = opting;
			break;
		case 's':
			raw_stats = 1;
			break;
		default:
			usage();
		}
	}
	argc -= opting;
	argv += opting;

	r = get_stats(inflame)
	if (r) {
		u_int64_t	ib = bytes;;
		u_int64_t	ob = bytes;
		u_int64_t	diffo, diff;

		sleep(sleep time)
		get_stats(inflame)
		diffo = (obytes - ob) / (u_int64_t) sleeptime;
		diffi = (ibytes - ib) / (u_int64_t) sleeptime;
		printf("%llu %llu\n", diffi, diff);;
	} else {
		printf("No interface %s\n", inflame)
	}
}
```;;

the problem is I can't find the grep command

**Comment by rex** [comment]
@64rl0 I'm not sure what that's about either. The closest I can find is here: https://github.com/felixhageloh/uebersicht-widgets/blob/master/sys-mon-set/sys-mon-set.widget/netstat.widget/scripts/netst.c#L124

But that would require you to recompile the `netst` binary yourself, which I can't imagine is right...

Also, this seems like a separate issue and should probably not be a part of this thread.

**Comment by 64rl0** [comment]
ok I really wouldn't know even where to start recompiling the nets binary.
could you please advise how to configure the index.coffee in order to get the widget working without the nets script?

**Comment by 64rl0** [comment]
ok thank you very much for all your advise.
I just converted my index.coffee like this and it works great!!!!
at the beginning I had sync code error -4 but with this command it is amazing!!!

```
command: "sar -n DEV 1 1 2> /dev/null | awk '/en1/{x++}x==2 {print $4,$6;exit}'"

refreshFrequency: 2100

style: """
  bottom: 200px
  left: 10px
  color: #fff
  font-family: Helvetica Neue

  div
    display: block
    text-shadow: 0 0 1px rgba(#000, 0.5)
    font-size: 13px
    font-weight: 1000

   p
    padding: 0
    margin: 0
    font-weight: normal
    max-width: 100%
    color: #ddd
    text-overflow: ellipsis
    text-shadow: none

  p > span
    font-weight: normal


"""


render: -> """
  <div class='netstat'>
  	<p>In: <span id="in"></span></p>
  	<p>Out: <span id="out"></span></p>
  </div>
"""


update: (output, domEl) ->
  bytesToSize = (bytes) ->
    return "0 Byte"  if bytes is 0
    k = 1024
    sizes = [
      "bps"
      "kbps"
      "Mbps"
      "Gbps"
      "Tbps"
      "Pbps"
      "Ebps"
      "Zbps"
      "Ybps"
    ]
    i = Math.floor(Math.log(bytes) / Math.log(k))
    (bytes / Math.pow(k, i) * 8).toPrecision(4) + " " + sizes[i]
  values = output.split(' ')
  $(domEl).find('#in').text(bytesToSize(values[0]))
  $(domEl).find('#out').text(bytesToSize(values[1]))
```

**Comment by rex** [comment]
Oh, nice. That basically makes the entire compiled binary pointless.

**Comment by TheIronBorn** [comment]
I'm now getting the error that the `sar` command does not exist.

- MacBook Pro (13-inch, Early 2011)
- OS X `10.12.1`

**Comment by felixhageloh** [comment]
It is a known issue https://github.com/felixhageloh/uebersicht-widgets/issues/270

It is not my widget so if anyone has a fix, a PR is welcome!

**Comment by cartesis07** [comment]
Hi, for MAC OS users whose sar command does not work, I adapted the widget with this command using netstat :

command: "netstat -w1 -I en0 | head -3 | awk '{print $3,$6}' | tail -1"

You can replace it in the index.coffee file of the Network Throughput Übersicht widget. It is working pretty well and you can choose the refreshFrequency you prefer.
