### ISSUE TITLE
Networkinginfo.widget - Thunderbolt to Ethernet Adapter  shows Not Connected

### ISSUE THREAD

**Issue by robertgranholm** [felixhageloh/uebersicht-widgets#124]
Sorry I'm not too familiar with github, so I'm not sure where to place this but the ethernet function doesn't seem to be working. I'm using a Retina Macbook Pro, thunderbolt ethernet adapter, and it's not showing, as seen here: http://take.ms/ciCjL

**Comment by felixhageloh** [comment]
It's the correct place! This is an older widget and doesn't have its own repo yet. 
There was a fix that I just merged in (https://github.com/felixhageloh/uebersicht-widgets/pull/97) ... maybe that will solve the issue (you'll have to re-download the widget).

**Comment by robertgranholm** [comment]
Thanks for the quick responses, so awesome, will make updates later as I
tinker.

-r



Always glad to help!


Robert Granholm
http://www.itarsenal.com
http://thelifedesignproject.com

**Comment by felixhageloh** [comment]
Thanks! Glad to see people using this stuff :)

**Comment by robertgranholm** [comment]
I noticed it will say (null) if not plugged in, if that's by design, cool with me, if not, keeping you informed.

**Comment by shawntothebee** [comment]
Changed line 32 in NetworkInfo.sh to:
service="Display Ethernet"
