### ISSUE TITLE
disk-usage.widget GiB instead of GB

### ISSUE THREAD

**Issue by robertgranholm** [felixhageloh/uebersicht-widgets#125]
GiB is used instead of GB. If this is intended, how do I change this?

**Comment by felixhageloh** [comment]
There is actually a difference :) http://www.andrewwhyman.com/blog/rants/mb-mib-gb-gib-what-the-differences-are-and-why-it-causes-confusion/

You can change it tho by changing the command slightly. At the very beginning you have

`df -h`

you can change that to 

`df -H`

I haven't tried it, but I think it should just work

**Comment by robertgranholm** [comment]
Eh it sorta worked. It changed Gib to G which I can live wth.

I noticed the amounts are way off as well before changing -h to -H. Unless
its measuring in something that I'm not expecting, see here:
http://take.ms/6ZNdg You can compare the amounts in the widget with the
desktop items

-r



Always glad to help!


Robert Granholm
http://www.itarsenal.com
http://thelifedesignproject.com

**Comment by robertgranholm** [comment]
Hmm also found that the memory widget gives me NaNMB as output under total.
I guess I need to understand UNIX better or something to fix these quirks.

-r



Always glad to help!


Robert Granholm
http://www.itarsenal.com
http://thelifedesignproject.com

**Comment by felixhageloh** [comment]
You can have a look at the `@humanize` method in the widget to change G to GB. 

The numbers seemed off because 1KiB is 1024 bytes and 1 KB is 1000 bytes. There is a good article about it here http://www.macworld.com/article/1142471/snow_leopard_math.html

It might actually be a good idea to switch the widget to GB since that is what people are more used to - I'll check with author of the widget!

The NaNMB thing means that the widget is trying to some math with something that isn't a number. Not sure if that helps to trace down the problem ...

**Comment by robertgranholm** [comment]
Ah, I thought it would be the byte difference, I'm aware of it, but not
enough to see that's what was being used in the code, it would certainly be
helpful to have what the system shows as available space, line up with what
the widget shows. At least the percentage available should be fairly
accurate, so I'll keep it on my desktop for now.

Not sure about the math issue, so I'm just removing the "Total" ... sort of
useless info, I know how much RAM is in my own machine.

-r



Always glad to help!


Robert Granholm
http://www.itarsenal.com
http://thelifedesignproject.com

**Comment by felixhageloh** [comment]
@agileadam what do you think about switching this to base 10 numbers (so GB not GiB), since it is what Mac OS uses these days as well?

**Comment by robertgranholm** [comment]
Thanks for the attention! @agileadam

**Comment by robertgranholm** [comment]
Any update here?

**Comment by agileadam** [comment]
@felixhageloh I think it's a good idea to make the switch.

There is a quick fix for this one... instead of using "df -h" we can use "df -H". I'm not sure if that's a Yosemite-only switch, but I'm assuming it's available to most version of OS X.

Can anyone verify?

**Comment by robertgranholm** [comment]
I'm afraid that didn't make a difference. Tested just now. NO change.

**Comment by felixhageloh** [comment]
I've updated the widget: It now shows GB by default, but you can switch to the GiB via an option flag. Let me know if you encounter problems and I'll open this issue again!
