### ISSUE TITLE
GitHub Notifications by type widget

### ISSUE THREAD

**Issue by mtscout6** [felixhageloh/uebersicht-widgets#126]
Here's a new widget for you: https://github.com/mtscout6/uebersicht-github-notifications

**Comment by soberstadt** [comment]
Wow, this looks really cool. Two small things. 
1. Do you need all of those octicon files? Or could you minimize those down some? 
2. Just an idea, it would be really cool if clicking the icons would open that page up in a browser. Is that possible @felixhageloh ?

**Comment by mtscout6** [comment]
Unfortunately there is not direct page for a list of notifications by those types. However, there is enough data there to display a list of each notification, then those items could have a link directly to the issue.

The icon files could be minimized, I haven't gone through the effort yet though of doing so. With that said I'm a big fan of pull requests :)

**Comment by soberstadt** [comment]
Well then maybe I or someone shall do that. But for now, the widget has been added and is on the site now. Thanks for the contribution!

**Comment by mtscout6** [comment]
Awesome, Thanks!
