### ISSUE TITLE
Spotify widget and artworks

### ISSUE THREAD

**Issue by Igor10k** [felixhageloh/uebersicht-widgets#127]
How about adding an optional artwork rendering for Spotify widget?

I tried doing it myself but I keep getting `stdout maxBuffer exceeded` because artworks are over 500KB limit. What's the reasoning behind making the buffer so small? This makes it impossible to create a widget that will show a photo for example.

**Comment by felixhageloh** [comment]
cool, I'll pass your suggestion to the author of the widget @ThomasBrace 

About the buffer size - the default is even smaller so I was reluctant to make this super big without knowing the consequences (probably there aren't many)

In the meantime, you could maybe solve this by just passing an image url (if at all possible)?

**Comment by Igor10k** [comment]
Sadly Spotify only provides image data.

https://cloudup.com/c8Iw4fqb1Cf

**Comment by felixhageloh** [comment]
I see! It's a bit of a roundabout solution but you could write that data to a file inside the widget folder. The command gets executed with the widgets folder as current working dir, so that should be feasible. After that, all files inside the widget folder are exposed as static assets so you can load them with `/path/to/file`

**Comment by Igor10k** [comment]
Damn, I can't find a way to convert AppleScript's `«data ..»` to `raw data`. Another thing that bothers me is that using this method the command will overwrite the file over and over again every 2 seconds. Not the best idea in case of SSD.

**Comment by felixhageloh** [comment]
had some spear time a played a bit with something that I've been wanting to do for a while: getting rid of the buffered approach and just stream things. Looks like it won't bee too hard, so chances are good that this will be fixed in the next release!

**Comment by felixhageloh** [comment]
I have a new build here https://www.dropbox.com/s/dpbxoh5m1urfuus/%C3%9Cbersicht-edge.app.zip?dl=0

It should fix this issue but might have a few bugs still. Give it a try if you like - it will be released once I fixed the specs and tested some more!

**Comment by Igor10k** [comment]
nice, no more buffer errors, but I still can't find a way to do render the artwork without writing it to file. Maybe someone with better understanding of AppleScript can help.

**Comment by felixhageloh** [comment]
I'm not sure what format the image data is in. If it is a base64 encoded string you can use a data-url (http://css-tricks.com/data-uris/). Otherwise you might have to use a canvas element and putImageData()
 (https://developer.mozilla.org/en/docs/Web/API/ImageData)

**Comment by Igor10k** [comment]
I thinks it's raw image data. AppleScript returns something like
```
«data TIFF4D4D002A00041EB8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFDFFFEFEFFFFFEFFFFFBFFFEF5F9FAEFF3F4EDF1F2FDFFFCFDFDFBFFFFFDFFFFFDFDFDFDFFFFFFFFFFFFFDFDFDFFF8F9FFFFFDF0F5F1E6F1EBDEEAE6E7F0EDF4F8F9FDFBFEE8E9EDE9EAEFF2F7FDD3DCE3B3C0C6ADB9B5AF......»
```

Using `putImageData` sounds like an option. I wonder though if there's a way within AppleScript to drop this `«data TIFF »` and return plain image data.

**Comment by TraderStf** [comment]
http://www.imagemagick.org/ should make it
