### ISSUE TITLE
Authentic Weather Widget

### ISSUE THREAD

**Issue by reduxd** [felixhageloh/uebersicht-widgets#130]
Haven't seen this one made for Übersicht. 

https://github.com/reduxd/authentic-ubersicht

**Comment by felixhageloh** [comment]
:D love it! 
I'd only need a screenshot (called screenshot.png) in the widget folder and I can add it to the gallery!

**Comment by felixhageloh** [comment]
did you manage to add a screenshot for this? Would be a pity not to add it to the gallery :)!

**Comment by reduxd** [comment]
added screenshot and updated to geolocation api. used the code from your pretty-weather widget :)

**Comment by felixhageloh** [comment]
awesome, I've added it! I also made pull request with some fixes for issues I encountered
