### ISSUE TITLE
sys-mon-set netstat.widget "error running command"

### ISSUE THREAD

**Issue by runlevelsix** [felixhageloh/uebersicht-widgets#131]
I've just installed Übersicht and installed the sys-mon-set widget. However, when I run the widget, I get this error on the screen (see screenshot below).

I traced it to the netstat widget. I can run the `netst` command from my terminal just fine, so I'm not sure what's going on. There aren't any prerequisites mentioned for Übersicht or the widget - do you think I'm missing an app, have a path error, or a conflict with an existing app? Any help would be appreciated.

I'm on Yosemite 10.10.2.

![screen shot 2015-02-27 at 1 28 37 pm](https://cloud.githubusercontent.com/assets/1616982/6420670/61a6c3dc-be85-11e4-93da-3f19253268d2.png)

**Comment by felixhageloh** [comment]
People have been having some issues with the netstat widget. You can follow the existing discussion here: Issue #122
