### ISSUE TITLE
Ping History Widget

### ISSUE THREAD

**Issue by bonus-tm** [felixhageloh/uebersicht-widgets#134]
Hello!
I found Übersicht recently and at long last created simple widget, that not just pings my sites, but displays history graphs. GeekTool and NerdTool are too hard to draw.
![screenshot](https://cloud.githubusercontent.com/assets/10289008/6449774/430028c2-c134-11e4-904e-8a00af35fe42.png)

Best wishes (:

**Comment by soberstadt** [comment]
I'm assuming the repo is: https://github.com/bonus-tm/uebersicht-ping-history.widget :smile:

**Comment by bonus-tm** [comment]
Oh, I am very sorry, at the last moment forgot to paste the link.
Yes, you're right, that is the correct repo.

**Comment by felixhageloh** [comment]
Thanks :) I've added it!
