### ISSUE TITLE
CPU Bar a'la Coby Chapple's Memory Bar

### ISSUE THREAD

**Issue by PerishableDave** [felixhageloh/uebersicht-widgets#136]
Hi!

I liked Coby Chapple's memory bar, so I decided to make a cpu bar from his widget.

https://github.com/PerishableDave/ubersicht-cpu-bar/

**Comment by felixhageloh** [comment]
Awesome, I've added it! Have a quick look at your screenshot - it gets a bit squashed on the website. If you want to resize it, you can find the best dimensions in the [readme](https://github.com/felixhageloh/uebersicht-widgets#readme)
