### ISSUE TITLE
Several widgets

### ISSUE THREAD

**Issue by hepabolu** [felixhageloh/uebersicht-widgets#138]
I've created several widgets. Please let me know if you'd like to include them in the gallery.

https://github.com/hepabolu/uebersicht-disk-bar

https://github.com/hepabolu/uebersicht-SimpleClock

https://github.com/hepabolu/uebersicht-uptime-bar

https://github.com/hepabolu/uebersicht-ShowTags

**Comment by felixhageloh** [comment]
Great thanks! I'm travelling right now but I will look into this when I have better WIFI again. Some of them look like duplicates of what is the gallery already, but I'll probably add the other ones!
