### ISSUE TITLE
Pretty Weather 'JSON Parse error: Unexpected identifier "Forbidden"' after update

### ISSUE THREAD

**Issue by zachschultz** [felixhageloh/uebersicht-widgets#140]
I just updated to the new übersicht and Pretty Weather now gives me the error `JSON Parse error: Unexpected identifier "Forbidden" after update`.

I do have an API key set up with forecast.io and Authentic Weather is working fine with it.

__Edit:__ The `index.coffee` in the zip file isn't that same as the one in the separate folder on the repo.

**Comment by felixhageloh** [comment]
thanks for pointing that out! Should be fixed now

**Comment by Ferdigan** [comment]
Hi, i try to install Pretty Weather, have APY key set up but this error appears: JSON Parse error. Unexpected Identifier "Cannot". Maybe it´s a silly error, sorry, but i could´t make it work. Thanks!

**Comment by felixhageloh** [comment]
@Ferdigan make sure you leave the quotes `"` around the API key and make sure to not use TextEdit (it replaces the quotes with a slightly different symbol). These are the common issues people run into
