### ISSUE TITLE
Morning Widget.

### ISSUE THREAD

**Issue by imRohan** [felixhageloh/uebersicht-widgets#144]
I've made a small widget that displays the current time as well as a greeting to the user. This is very similar to the popular Chrome extension, [Momentum] (http://momentumdash.com).

The git repository is located here [Link](https://github.com/imRohan/ubersicht-morning.widget)

Cheers, 

-R

**Comment by felixhageloh** [comment]
Looks great! One thing you could consider doing is using a terminal command to get the user's name (instead of having to change it in the widget). You could use

```
command: "whoami"
```

or to get the full name

```
command: "finger `whoami` | awk -F: '{ print $3 }' | head -n1 | sed 's/^ //'"
```

**Comment by imRohan** [comment]
That's a great idea.

I've updated the widget. It now grabs the first name of the logged in user.

**Comment by felixhageloh** [comment]
Great thanks! Part of the reason for suggesting this was to make the widget more distinct from the Big Clock widget. I think now it adds enough functionality to be added as a separate widget in the gallery. It is up now!

**Comment by Pearcey1409** [comment]
Hello can you please help me? I downloaded this widget and I love it. I have two displays it works perfectly on my laptop screen as is dead centre. But on my big TV external display the widget is not in the middle and slightly to the side which is driving me crazy, how can I move it to the correct position? Please help! thanks 
![screenshot 2019-01-04 at 13 44 57](https://user-images.githubusercontent.com/46364312/50672999-f9f69800-1026-11e9-8505-d60c759e5fa6.png)
