### ISSUE TITLE
Updates to OmniFocus Widget

### ISSUE THREAD

**Issue by fitzagard** [felixhageloh/uebersicht-widgets#145]
The following updates have been made to omnifocus widget (https://github.com/fitzagard/omnifocus-widget):

 * Fixed a bug with previously deferred tasks
 * Task Titles are now clickable

**Comment by soberstadt** [comment]
The way the widget gallery works with linked repos is that we link directly to your zip and screenshot file in your repo. So if you update the zip there, it will be updated on the gallery page.

**Comment by fitzagard** [comment]
Okay thanks!
