### ISSUE TITLE
Markdown Cheat sheet

### ISSUE THREAD

**Issue by jacksonfylle** [felixhageloh/uebersicht-widgets#147]
Hi,
https://github.com/jacksonfylle/Ubersicht

**Comment by felixhageloh** [comment]
Thanks for submitting! Please make sure you have a screenshot called `screenshot.png` so I can add it to the gallery

**Comment by jacksonfylle** [comment]
Done,
Thanks

**Comment by felixhageloh** [comment]
Great screenshot is fixed now. I just noticed that the manifest file also needs to be called `widget.json`. Sorry this is all for the build script to add it to the gallery.

**Comment by jacksonfylle** [comment]
Should be ok.
Sorry for that

**Comment by felixhageloh** [comment]
all ok now! It is online
