### ISSUE TITLE
Google Earth View Background

### ISSUE THREAD

**Issue by Maggick-** [felixhageloh/uebersicht-widgets#148]
https://github.com/Maggick-/earth_view

Get a random image from https://earthview.withgoogle.com/

Sets as background.

Slight issue with different screen size, may need to be addressed

**Comment by felixhageloh** [comment]
Thanks! I've added it

**Comment by djbrooks111** [comment]
This was a problem with the command in which the random number in the command was not being regenerated for each refresh of Ubersicht.  This has been fixed in my pull request (https://github.com/Maggick-/earth_view/pull/3) and so I just wanted to bring this to your attention.
