### ISSUE TITLE
simple-stocks.widget [minor] issue with suggested fix

### ISSUE THREAD

**Issue by endowdly** [felixhageloh/uebersicht-widgets#149]
If the respective market is closed when the widget is loaded, there is no change indicator and as such, the script will always display the red 'down' class. This doesn't always give the proper indication for a stock's behavior.

In the update function, if you change 'direction' from:  
```coffeescript
    direction = if (change.charAt(0) == '+') then 'up' else 'down'
```  
to
```coffeescript
    direction = if (changepct.charAt(0) == '+') then 'up' else 'down'
```  
The code will then parse color from 'changepct', which should always load and provide the proper color :)

**Comment by felixhageloh** [comment]
Thanks for the suggested fixes! If can add them in if the author @agileadam agrees!

**Comment by agileadam** [comment]
Thanks endowdly.
I can confirm that this fix works.

@felixhageloh, I'd say that is go for launch :)

**Comment by felixhageloh** [comment]
done!
