### ISSUE TITLE
New Widget for showing next events of multiple Google Calendars

### ISSUE THREAD

**Issue by dimitri-koenig** [felixhageloh/uebersicht-widgets#150]
Here we go: https://github.com/dimitri-koenig/uebersicht-widget-for-google-cal

**Comment by felixhageloh** [comment]
Thanks for the awesome widget! How would you feel about submitting your improvements as a pull request to this widget: http://localhost:3030/#gcal-widget ?
If not I can just add this widget as well

**Comment by dimitri-koenig** [comment]
I thought about it at first, but then: it's not just an addition. The code is completely different. The features are different (multiple feeds, and the entries are not limited to 5). So I would prefer to have it published as a standalone widget.

**Comment by felixhageloh** [comment]
added it!
