### ISSUE TITLE
New widget - jenkins CI

### ISSUE THREAD

**Issue by piresbruno** [felixhageloh/uebersicht-widgets#151]
Simple and clean jenkins CI  widget available here -> https://github.com/piresbruno/uebersicht-jenkins

**Comment by felixhageloh** [comment]
Thanks! Please make sure to have a file called screenshot.png and a zip file of your widget, called widget.zip, so I can add it to the gallery.

**Comment by piresbruno** [comment]
done

**Comment by felixhageloh** [comment]
Thanks, looks good now! I just noticed you are also missing the `widget.json` file (widget manifest) - sorry the build script for the website needs these

**Comment by piresbruno** [comment]
widget.json added to the repository.

**Comment by felixhageloh** [comment]
thanks, it's up now!
