### ISSUE TITLE
Is it possible to use the Notification API?

### ISSUE THREAD

**Issue by piresbruno** [felixhageloh/uebersicht-widgets#153]
Hi,

Just wondering if it is possible to use the html Notification API with Uebersicht widgets.

Best

**Comment by felixhageloh** [comment]
I wouldn't expect that it works out of the box - it will probably require some changes to the app itself

**Comment by paulbhartzog** [comment]
You can trigger notifications via Applescript.  Ping me if you want examples and I'll share some. :-)

**Comment by felixhageloh** [comment]
thanks @paulbhartzog. @piresbruno  does this help/answer your question?

**Comment by piresbruno** [comment]
yes, thanks @felixhageloh  and @paulbhartzog
