### ISSUE TITLE
Process Bar widget

### ISSUE THREAD

**Issue by gregmajor** [felixhageloh/uebersicht-widgets#154]
I've created a process bar that is intended to compliment Coby Chapple's nice [Memory Bar Widget](https://github.com/cobyism/ubersicht-memory-bar). You can find it in my [GitHub repository](https://github.com/gregmajor/ubersicht-widgets).

Great tool!

Greg

**Comment by felixhageloh** [comment]
Thanks, looks great! I am hesitant to add it to the widget gallery since it looks very similar to the Top CPU widget (in an effort to keep the widget gallery focused). Let me know if I am missing something tho and I can add it!

**Comment by gregmajor** [comment]
You're right, it is quite similar. Somehow I managed to miss that. No big deal.

**Comment by gregmajor** [comment]
Oh, if anyone stumbles across this and wants to use mine, the URL is now [here](https://github.com/gregmajor/ubersicht-process-bar-widget).
