### ISSUE TITLE
Outdated Brew Formulae widget

### ISSUE THREAD

**Issue by gregmajor** [felixhageloh/uebersicht-widgets#157]
I've created an outdated brew formulae widget that shows a list of the [Homebrew](http://brew.sh) formulae that are out of date on your system. You can find it in [my GitHub repository](https://github.com/gregmajor/ubersicht-widgets/tree/master/outdated-brew-formulae).

Great tool!

Greg

**Comment by felixhageloh** [comment]
Thanks again :) I'll need a widget zip file so that I can add it to the gallery (for people to download it). Also  could you put it in a separate repo? Sorry - using automated build scripts for this, so the requirements are quite rigid

**Comment by gregmajor** [comment]
Dang it! Forgot about the zip file. I'll take care of that and the repo
today.

**Comment by gregmajor** [comment]
Okay, I've pulled this to a new repo ([found here](https://github.com/gregmajor/ubersicht-outdated-brew-formulae-widget)) and added the zip file.

Thanks!

**Comment by felixhageloh** [comment]
excellent, I've added it!
