### ISSUE TITLE
Mandarin Chinese Word of the Day Widget

### ISSUE THREAD

**Issue by himynameisbeni** [felixhageloh/uebersicht-widgets#161]
I modified the German Word of the Day Widget to create a Mandarin Chinese Word of the Day Widget.
https://github.com/himynameisbeni/Mandarin-Chinese-Word-Of-The-Day-widget

**Comment by felixhageloh** [comment]
Sorry for getting back to you so late and thanks for sharing your widget! Please check that the widget conforms to the specs in the readme (i.e. it needs a zip file screenshot etc,) - otherwise I can't add it to the gallery

**Comment by himynameisbeni** [comment]
No worries, I'm just excited to get some code up some people might use as a comp sci freshman. It should comply to your specifications now, thanks for you time.

**Comment by felixhageloh** [comment]
just had a quick look and seems like you are still missing the manifest file `widget.json`

**Comment by himynameisbeni** [comment]
Sorry about that, I've added a widget.json it should be all okay now.

**Comment by felixhageloh** [comment]
thanks! I've added it!
