### ISSUE TITLE
Blurred background blocs Widget

### ISSUE THREAD

**Issue by atika** [felixhageloh/uebersicht-widgets#165]
Hi, I made a new widget to create blurred background zones.
https://github.com/atika/Ubersicht-Blur
![screenshot](https://cloud.githubusercontent.com/assets/1880360/8532836/f5acf822-2428-11e5-86e0-f6154c9586ea.png)

**Comment by felixhageloh** [comment]
thanks for another great looking widget! Added it

**Comment by atika** [comment]
Thanks Felix, I had to find a tip for not having the border blurred. I am working on other widget but I still have issues...
