### ISSUE TITLE
Make iStats working with Übersicht. 

### ISSUE THREAD

**Issue by mvaneijgen** [felixhageloh/uebersicht-widgets#166]
I thought it would be easy to get this working, but im just not that created with terminal commands. I wanted to get the temperature stats of my make on my desktop and it found [this Ruby gem iStats](https://github.com/Chris911/iStats), but I just can't seem to get it to work. I either get `command not found` , `warning not rendering method` or `nothing shows at all`

Any help is greatly appreciated.

**Comment by baberthal** [comment]
I (sort of) got this to work just now. The problem is that the bash shell spawned by Uebersicht doesn't know where the gem is, so you have to tell it. I don't know if you use homebrew and/or rvm, but I got it working like this:

```
command: "/usr/local/bin/ruby /usr/local/lib/ruby/gems/2.2.0/gems/iStats-1.0.1/bin/istats"
```

Please note the paths to your system ruby and the installed gem might be different for you.

**Comment by mvaneijgen** [comment]
Thanks! All I could find was: put this on the frist line of your command `#!/usr/bin/ruby`. When googling my problem, but an hour later I finally figured out where my Ruby and gems are installed. And yes my path was totally different. Here is mine: `command: "/usr/bin/ruby /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/iStats-1.0.1/bin/istats"`

But I see your point of "I (sort of) got this to work", here is what it looks like 

![istats with Übersicht](http://i.imgur.com/d4qdh51.jpg)

**Comment by baberthal** [comment]
Yup! That's what I meant by 'sort of'. You could always pipe the output through awk to grab the stats you want to display, then style them with css. Glad I could help!

**Comment by atika** [comment]
With the command `smc` included on the application `smcfancontrol` you can retrieve somes informations like cpu temperature, fan speed.

An exemple for cpu temperature
```
#!/bin/bash

smcfancontrol="/Applications/smcFanControl.app/Contents/Resources"

if [[ -d $smcfancontrol ]]; then
    # Temperature in Celsus
    $smcfancontrol/smc -k TC0D -r | sed 's/.*bytes \(.*\))/\1/' |sed 's/\([0-9a-fA-F]*\)/0x\1/g' | perl -ne 'chomp; ($low,$high) = split(/ /); print (((hex($low)*256)+hex($high))/4/64); print "\n";'
else
    exit 1
fi
```
More info on codes to retrieve info here : https://github.com/hholtmann/smcFanControl/tree/master/smc-command

**Comment by mvaneijgen** [comment]
@atika thanks, but I was looking for a script that could replace `smcfancontrol`

**Comment by roele** [comment]
@mvaneijgen Looks we had the same idea. You might be interested in https://github.com/roele/istats.widget.

**Comment by mvaneijgen** [comment]
@roele nice thanks! Works great. I had to modify it, because my macbook pro 13" only has one fan.

**Comment by mvaneijgen** [comment]
@roele nice thanks! Works great. 

I had to modify it, because my macbook pro 13" only has one fan.

**Comment by roele** [comment]
@mvaneijgen Glad you like it. Feel free to open an issue, should be relatively easy to make this dynamic.
