### ISSUE TITLE
Earth View 2.0

### ISSUE THREAD

**Issue by cytec** [felixhageloh/uebersicht-widgets#169]
as it seems like earth view widget is not working anymore... 

I've made my own, which also shows location data (Country & Administration Area) at the bottom right.

https://github.com/cytec/earth-view-uebersicht

**Comment by felixhageloh** [comment]
Great thanks! Is it maybe an idea to make a pull request for the original widget with your fixes/improvements? Or, since the original one is broken as you say, maybe we can contact the author and see if we can take it down and add yours instead.

**Comment by cytec** [comment]
@felixhageloh either way is ok for me, id go with what you prefer
maybe @Maggick- pulls my changes or we switch it... 

anyway i've changed a few things i've missed like proper image scaling and also started implementing some kind of "history" like earth view does it...

**Comment by felixhageloh** [comment]
cool let me know then what you and @Maggick come up with

**Comment by felixhageloh** [comment]
I'll close this one for now - please open a new issue when there are any updates
