### ISSUE TITLE
Alternate

### ISSUE THREAD

**Issue by travtrigs** [felixhageloh/uebersicht-widgets#172]
Hey man, i was working around with the calendar widget and i edited it so that it includes the days of the week in the previous and next months in a grey text instead of there just being blank spaces... i don't know if you'd like me to send it to you so you can put it up or something. let me know. spent a lot of time working on it so was hoping it might be useful to some people

**Comment by soberstadt** [comment]
Go ahead and make a pull request from your fork with the changes into this repo, and we'll have a look. If it's acceptable, we'll merge it for everyone.
