### ISSUE TITLE
Unread Messages widget

### ISSUE THREAD

**Issue by travtrigs** [felixhageloh/uebersicht-widgets#174]
https://github.com/travtrigs/Unread-Messages.widget

Displays number of unread messages.

<img width="258" alt="screenshot" src="https://cloud.githubusercontent.com/assets/13620298/9050173/b827fae6-3a18-11e5-9e9e-5dba83d2656f.png">

**Comment by felixhageloh** [comment]
thanks for submitting! My build script breaks on the `widget.json` file for this one. It contains `“` instead of regular double quotes `"` - could be your text editor (TextEdit is known for doing that). Could you change those and I can try to add it again
