### ISSUE TITLE
Circular RAM Wiget

### ISSUE THREAD

**Issue by zanderp** [felixhageloh/uebersicht-widgets#175]
Hello,
Sorry for adding them one by one. 
here is another to add to the gallery

How can I contract you? Can we connect on skype or something I have something to propose to you.

https://github.com/zanderp/circular-ram-widget

**Comment by felixhageloh** [comment]
Hey, no problem - it is better to add them this way!
Yeah sure, my Skype name is felixhageloh. I might not have much time today, but I'll get back to asap!

**Comment by felixhageloh** [comment]
Added your widget btw!
