### ISSUE TITLE
app-launcher.widget

### ISSUE THREAD

**Issue by travtrigs** [felixhageloh/uebersicht-widgets#176]
This widget adds an application launcher to the desktop which includes simple, white icons to fit with the theme of most other widgets and is highly customizable to allow users to change the layout of the widget, choose which applications can be launched, and add their own icons.

https://github.com/travtrigs/app-launcher.widget
<img width="258" alt="screenshot" src="https://cloud.githubusercontent.com/assets/13620298/9130894/9c5a6c4c-3cb4-11e5-9bfb-75c7930c4ecf.png">

**Comment by felixhageloh** [comment]
added!
