### ISSUE TITLE
folder-launcher.widget

### ISSUE THREAD

**Issue by travtrigs** [felixhageloh/uebersicht-widgets#177]
This widget adds a folder launcher to the desktop which includes simple, white icons to fit with the theme of most other widgets and is highly customizable to allow users to change the layout of the widget, choose which folders can be opened, and add their own icons.
 
https://github.com/travtrigs/folder-launcher.widget
<img width="616" alt="screenshot" src="https://cloud.githubusercontent.com/assets/13620298/9130908/bfbffe04-3cb4-11e5-95ee-9b78056d5857.png">

**Comment by felixhageloh** [comment]
added!
