### ISSUE TITLE
Solar System display widget

### ISSUE THREAD

**Issue by travtrigs** [felixhageloh/uebersicht-widgets#180]
This widget displays an image of the solar system with the current locations of all the planets. https://github.com/travtrigs/solar-system.widget
<img width="554" alt="screen shot 2015-08-09 at 10 24 11 pm" src="https://cloud.githubusercontent.com/assets/13620298/9158467/6170334a-3ee5-11e5-9ad8-f3485bf468f8.png">

**Comment by travtrigs** [comment]
Planets beyond the asteroid belt have a smaller scale, to fit better. Can be configured.

**Comment by felixhageloh** [comment]
added!
