### ISSUE TITLE
Evangelion Style Widget

### ISSUE THREAD

**Issue by jeticg** [felixhageloh/uebersicht-widgets#181]
Hello, I wrote this to impress my girlfriend (she is a huge fan to the Evangelion comics). I think it's pretty beautiful, especially the animation when your battery drops without charging or cpu usage exceeds 90%.
https://github.com/jeticg/Evangelion-Uebersicht-Widget
![screenshot](https://cloud.githubusercontent.com/assets/7542292/9553445/6cd53ecc-4dbf-11e5-8942-4f9ce6c78520.png)

**Comment by zanderp** [comment]
You need to follow the instructions of adding a widget. 

Make a widget-name.zip where you put the widget and a screenshot.png with how it looks. Thanks. 

De la:"Jetic Gu" <notifications@github.com>
Data:Vin 28 aug. 2015 la 9:01 PM
Subiect:[uebersicht-widgets] Evangelion Style Widget (#181)

Hello, I wrote this to impress my girlfriend (she is a huge fan to the Evangelion comics). I think it's pretty beautiful, especially the animation when your battery drops without charging or cpu usage exceeds 90%.
https://github.com/jeticg/Evangelion-Uebersicht-Widget
￼

**Comment by jeticg** [comment]
Done

**Comment by felixhageloh** [comment]
Awesome looking widget, thanks for submitting (and fixing it to meet the specs)! I've added it
