### ISSUE TITLE
A DiskUsage bar widget.

### ISSUE THREAD

**Issue by dinever** [felixhageloh/uebersicht-widgets#182]
Hi,

This is a disk usage bar widget, designed to go with [ubersicht-memory-bar](https://github.com/cobyism/ubersicht-memory-bar).

[https://github.com/dinever/DiskUsage-Bar-Widget](https://github.com/dinever/DiskUsage-Bar-Widget)

<img width="337" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1311594/9702967/c2d5a888-5441-11e5-89dd-88a79478f3f5.png">

**Comment by felixhageloh** [comment]
Thanks and sorry for the late reply! I've added it
