### ISSUE TITLE
Bluetooth battery usage

### ISSUE THREAD

**Issue by gschrader** [felixhageloh/uebersicht-widgets#185]
https://github.com/gschrader/ubersicht-bluetooth-battery-bar

**Comment by felixhageloh** [comment]
Thanks for submitting! Can you add a zip file for this widget (details are in the README), then I can add it

**Comment by gschrader** [comment]
Oops, I think I have the proper zip file in place now.

**Comment by felixhageloh** [comment]
looks good, I've added it!

**Comment by gschrader** [comment]
Cool, thanks!
