### ISSUE TITLE
Battery Monitor with Charge Cycle, Time to Recharge and Percentage Left Widget

### ISSUE THREAD

**Issue by synle** [felixhageloh/uebersicht-widgets#186]
I find myself in need of a unified UI for battery widget but most of the current battery widget looks a little out place. So I decided to make this widget that allows showing of more information including percent time left, time to recharge, charge cycle, etc.

URL
https://github.com/synle/ubersichtBatteryMeter

Screenshot
![1](https://cloud.githubusercontent.com/assets/3792401/10127315/a11be6e8-6554-11e5-8216-8b68bb499e32.png)

Now you will have a more unified look and feel.
![screen shot 2015-09-27 at 8 18 32 pm](https://cloud.githubusercontent.com/assets/3792401/10127342/039e5ba2-6555-11e5-8198-4f7746cfaaf6.png)

**Comment by zanderp** [comment]
Please see the widget submission instructions in the ubersicht-widgets repo readme file.

Trimis din Yahoo Mail pe Android

De la:"Sy Le" <notifications@github.com>
Data:Lun 28 sept. 2015 la 6:19 AM
Subiect:[uebersicht-widgets] Battery Monitor with Charge Cycle, Time to Recharge and Percentage Left Widget (#186)

I find myself in need of a unified UI for battery widget but most of the current battery widget looks a little out place. So I decided to make this widget that allows showing of more information including percent time left, time to recharge, charge cycle, etc.

URL
https://github.com/synle/ubersichtBatteryMeter

Screenshot
￼

Now you will have a more unified look and feel.
￼

**Comment by felixhageloh** [comment]
Hi and thanks for submitting! As @zanderp pointed out widgets need to conform to the specifications in the readme so that I can add them (I'm using an automated build script).

**Comment by felixhageloh** [comment]
I'll close this one for now - you can reopen another issue if you want to submit again
