### ISSUE TITLE
New iTunesMiniPlayer widget

### ISSUE THREAD

**Issue by jscampos** [felixhageloh/uebersicht-widgets#189]
Hi Guys,

I created a new widget that is hosted here: https://github.com/jscampos/iTunesMiniPlayer.widget

I tested and I think it is time for it to be public, I'm open suggestions and feedback.

**Comment by soberstadt** [comment]
Hi Jose,

That looks like a useful widget! First off, can you update you screenshot to fit the specified size? https://github.com/felixhageloh/uebersicht-widgets#screenshot

Thanks!

**Comment by jscampos** [comment]
I have a 21:9 display, so what dimension would you rather I follow? width or height?

**Comment by felixhageloh** [comment]
hey @jscampos, also thanks for sharing your widget! The best is to cut out a section of your screenshot that contains the widget. It will be used as the main image in the [gallery](http://tracesof.net/uebersicht-widgets/) so it is good to get a closeup impression of your widget (and of course it will avoid the issue you have with the aspect ratio)

**Comment by jscampos** [comment]
Done, let me know if there is anything else for me to do.

**Comment by felixhageloh** [comment]
All good now, I've added it! Thanks again
