### ISSUE TITLE
Word Clock Widget

### ISSUE THREAD

**Issue by wrutkowski** [felixhageloh/uebersicht-widgets#190]
Hi All,

I was inspired by Instructables http://www.instructables.com/id/Sleek-word-clock/ to create word clock, but wanted to have it digital for Übersicht.

Here it is:
https://github.com/wrutkowski/ubericht-wordclock

Suggestions highly welcome!

Thanks,
Wojtek

**Comment by felixhageloh** [comment]
Thanks looks good, I've added it! Since you've asked for suggestions: Maybe by using (more?) opacity  on the inactive words you can mimic the look of the original even closer
