### ISSUE TITLE
Set-Networking-Fork

### ISSUE THREAD

**Issue by PapyPev** [felixhageloh/uebersicht-widgets#192]
Hello ! 

I created a Fork of <a href="https://github.com/brookesdjb/Set-networking.widget">Set-Networking.widget</a> based on style from <a href="https://github.com/dinever/DiskUsage-Bar-Widget">DiskUsage-Bar-Widget</a>.

The Widget sources are here : <a href="https://github.com/PapyPev/Set-networking.widget">Sources Github</a>

Enjoy :)

**Comment by felixhageloh** [comment]
Hi, thanks for sharing! 
Since this is a fork/styling option of an existing widget I usually suggest to first contact the original author (@brookesdjb) and see if they want to merge in the fork. If you or brookesdjb disagree I can still add this to the gallery

**Comment by felixhageloh** [comment]
I'll close this one for now - please open a new ticket if you have any updates or still want this added
