### ISSUE TITLE
xkcd-random.widget

### ISSUE THREAD

**Issue by PapyPev** [felixhageloh/uebersicht-widgets#193]
Hello !

We made a new widget to show a random xkcd comic every 10 min and alt text.
You can find our sources here : <a href="https://github.com/PapyPev/xkcd-random.widget">Github Sources</a>

It's based on <a href="https://github.com/dalemanthei/uebersicht-widgets/tree/master/xkcd">original sources from dalemanthei</a> and <a href="https://github.com/dinever/DiskUsage-Bar-Widget">original design from dinever</a>

Enjoy,
PapyPev

**Comment by felixhageloh** [comment]
thanks, I've added it!
