### ISSUE TITLE
To Do List Widget Question

### ISSUE THREAD

**Issue by Yuyuko** [felixhageloh/uebersicht-widgets#194]
I downloaded the todolist widget and I'm not sure how to customize it. Any help is appreciated. Thanks.

**Comment by felixhageloh** [comment]
Is you question about editing widgets in general or for this specific widget?
You can get started by opening the `index.coffee` file inside the widget folder and poke around there. 
I didn't write this widget, but it looks like it is looking for a file called `ToDo.list` inside the same folder, where you can edit your todo list items. Hope this helps!

**Comment by felixhageloh** [comment]
I'll close this one for now - let me know if you have other questions
