### ISSUE TITLE
Last.FM Widget

### ISSUE THREAD

**Issue by patrickhpan** [felixhageloh/uebersicht-widgets#196]
I've created a Last.FM widget, found here: http://git.patrickpan.com/patrick/lastfm-ubersicht
Thanks!

**Comment by felixhageloh** [comment]
Hey thanks for sharing your widget - looks great! Any chance you could put it on GitHub? The widget gallery is currently tightly coupled to GitHub and won't work with GitLab

**Comment by patrickhpan** [comment]
Done! https://github.com/patrickhpan/lastfm-ubersicht/

**Comment by felixhageloh** [comment]
thanks - I've added it!
