### ISSUE TITLE
StackExchange widget

### ISSUE THREAD

**Issue by d4rkd3v1l** [felixhageloh/uebersicht-widgets#197]
I created two widgets, one for StackExchange stats (e.g. StackOverflow):
https://github.com/d4rkd3v1l/uebersicht-stackexchange.widget

The other one for git repo stats:
https://github.com/d4rkd3v1l/uebersicht-git-stats.widget

Both really need a nice graphical design! But I'm just a developer.. ;-)

**Comment by felixhageloh** [comment]
Thanks and sorry for the late reply. I've added them!
