### ISSUE TITLE
iStats Widget

### ISSUE THREAD

**Issue by roele** [felixhageloh/uebersicht-widgets#198]
Created a simple iStats widget showing SMC stats.
https://github.com/roele/istats.widget

Preview:
<img width="1680" alt="istats widget" src="https://cloud.githubusercontent.com/assets/181773/11319253/e17bd544-9070-11e5-8c91-c32705435811.png">

**Comment by felixhageloh** [comment]
thanks for submitting! Can you add a screenshot.png file to your repo (you can check the readme for details). It is needed to be displayed in the widget gallery

**Comment by felixhageloh** [comment]
I noticed a few other files missing as well - basically make sure to check https://github.com/felixhageloh/uebersicht-widgets#readme

**Comment by roele** [comment]
Thanks @felixhageloh. I followed up on the requirements for inclusion accordingly.

**Comment by felixhageloh** [comment]
alright, I've added it. Widget looks great btw!
