### ISSUE TITLE
HTML5 video widget

### ISSUE THREAD

**Issue by paulbhartzog** [felixhageloh/uebersicht-widgets#199]
I love Übersicht!

Here's hoping you will share my widget:  https://github.com/paulbhartzog/ubersicht-video-widget

fwiw, please contact me by email as I would like to get more involved with Übersicht and I can't find your email address anywhere.  thx. Mine is paulbhartzog@paulbhartzog.org

**Comment by felixhageloh** [comment]
Thanks, glad you like the app! 
I only need a manifest file to be able to add the widget (details in the readme). I'll also ping you via email!

**Comment by paulbhartzog** [comment]
Manifest is in there:
https://github.com/paulbhartzog/ubersicht-video-widget/blob/master/video.json


-------------------------------------------------------------------------------
http://www.PaulBHartzog.org
PaulBHartzog@PaulBHartzog.org              (o|o)
-------------------------------------------------------------------------------
If you bow deeply to the universe, it bows back.
               ~ Ueshiba Morihei

The Universe is made up of stories, not atoms.
               ~ Muriel Rukeyser

Act as if what you do makes a difference. It does.
               ~ William James

We come out of the world, not into it.
               ~ Alan Watts

If the path before you is clear, you're probably on someone else's
               ~ Joseph Campbell

Perceive differently, then you will act differently.
               ~ Paul B. Hartzog
-------------------------------------------------------------------------------

**Comment by felixhageloh** [comment]
I see! The bull script expected the file to be called `widget.json` but I made it more lenient. Widget has been added!

**Comment by paulbhartzog** [comment]
Release v1.2 is at https://github.com/paulbhartzog/ubersicht-video-widget/releases/tag/1.2

I renamed the files in https://github.com/paulbhartzog/ubersicht-video-widget

I also changed the json file which has the "name" that gets displayed on http://tracesof.net/uebersicht-widgets/

Please update http://tracesof.net/uebersicht-widgets/

thx

**Comment by felixhageloh** [comment]
should be updated now!
