### ISSUE TITLE
Solarized iTunes Widget

### ISSUE THREAD

**Issue by yohnnyjoe** [felixhageloh/uebersicht-widgets#201]
Übersicht is great, even if it does mess with my tab completion.  I was hoping you could add my widget to the community.  I think it's all there.
https://github.com/yohnnyjoe/SolTunes.widget

**Comment by felixhageloh** [comment]
Thanks for sharing, I've added it!
You mentioned it messes with your tab completion - can elaborate?

**Comment by yohnnyjoe** [comment]
Thanks Felix,
The umlaut in Übersicht makes it so can't type `Übe <tab>/widg <tab>` in terminal and be in widgets folder.  Really not an issue for me though.  Thanks again and glad to be a part of the Übersicht-widgets community.

**Comment by felixhageloh** [comment]
Oh right :) - just checking if it was a bug. You can change the widget folder path to anything you like in the preferences btw.
Thanks again for sharing your widget!
