### ISSUE TITLE
APOD widget

### ISSUE THREAD

**Issue by KiwiSkunk** [felixhageloh/uebersicht-widgets#202]
Hi. First attempt at this (GitHub, Perl, etc) so I hope I have it correct. I built this for myself and thought I should share it.
https://github.com/KiwiSkunk/apod-view.widget

**Comment by felixhageloh** [comment]
Thanks for sharing! It is almost correct: you just need to move the zip file, screenshot and manifest json into the root of the repo (example: https://github.com/felixhageloh/pretty-weather). 

After that I can add it :)

**Comment by KiwiSkunk** [comment]
Hi Felix. I think it's sorted now.

**Comment by felixhageloh** [comment]
all good now, I've added it. Thanks again!
