### ISSUE TITLE
Downloads not showing up for all widgets

### ISSUE THREAD

**Issue by yohnnyjoe** [felixhageloh/uebersicht-widgets#203]
Is there a reason some of the widgets don't have downloads showing up on the gallery page? I know it's a little vain, but I'd like to see my downloads too if possible.  If it's something I can edit on my end I'd be happy too. 
Thanks,
John

**Comment by felixhageloh** [comment]
Could be a bug! Which widget are you referring to, so I can see if I can reproduce

**Comment by yohnnyjoe** [comment]
Mine is SolTunes but I've noticed iStats doesn't show downloads as well.

**Comment by felixhageloh** [comment]
I found and fixed the issue! You should have received an email about it as well. Please let me know if you didn't receive it, because I emailed a few others that were affected by this bug. 

Thanks for reporting and sorry for the lost download counts!
