### ISSUE TITLE
New widget for use with Lightroom photos

### ISSUE THREAD

**Issue by evanfuture** [felixhageloh/uebersicht-widgets#205]
Hi everyone!  I made this widget over the last few weeks.  It's probably not the most elegant of implementations, but I hope you find it useful anyway.  At the very least it should save some time.

https://github.com/evanfuture/lightroom-latest.widget

Requires the companion node-module, https://github.com/evanfuture/lr-latest, and ImageMagick to be installed.  Please let me know your thoughts!

**Comment by felixhageloh** [comment]
Awesome, thanks for sharing I've added it!
You could try to install most of the dependencies locally (especially the node module), i.e. include them in your widget and use relative paths. OTH, since people need Adobe Photoshop Lightroom installed anyway, this might bring too many gains

**Comment by evanfuture** [comment]
Thanks!  I'll keep improving it certainly.
