### ISSUE TITLE
Updated APOD widget

### ISSUE THREAD

**Issue by KiwiSkunk** [felixhageloh/uebersicht-widgets#206]
Hi Felix

I updated APOD-view to handle videos on their site. Can you replace the current version or add this one please?

Cheers Andrew

**Comment by felixhageloh** [comment]
If it is just a code change, updates should happen automatically once you push them to your widget's repo. The only updates that require work from my end is when you change something in the widget manifest file. In any case I ran updates today so everything should be up to date!
