### ISSUE TITLE
Sprichwortrekombinator-Widget

### ISSUE THREAD

**Issue by moontan** [felixhageloh/uebersicht-widgets#207]
https://github.com/moontan/uebersicht-widgets.git
Hey, I just made my first Übersicht widget :-) Feel free to have a look and let me know if you find any errors. I'd be chuffed to see this added to the widget pool (I'm convinced it's an essential).
I'm unsure if I should leave the font out of the package. If the people at Lindenthal agreed I'd in fact be tempted to add all of their Gothic fonts and write a little config script for the widget.

**Comment by felixhageloh** [comment]
Hi thanks for sharing your essential widget ;)
To answer your question about the font: If you have the rights to redistribute it (maybe by adding the required license to your widget) it would indeed be the most convenient to include it directly in the widget. 

I only noticed one thing; you called your repo `uebersicht-widgets`, suggesting that there could be more. However, the idea is to have one repo per widget. The repo layout is actually fine, so I could add it as is, but I thought maybe you want to rename your repo to the widget name first. Let me know!

**Comment by felixhageloh** [comment]
closing this for now
