### ISSUE TITLE
Menubar replacement with currently playing track

### ISSUE THREAD

**Issue by callahanrts** [felixhageloh/uebersicht-widgets#208]
Getting the current track from Soundcloud or Youtube requires a few extra setup steps. All documented here https://github.com/callahanrts/bar

**Comment by felixhageloh** [comment]
Looks interesting! Thanks for sharing - I've added it

**Comment by nueh** [comment]
The screenshot is a tiny bit heavy, I think... (7.9 MB)

**Comment by callahanrts** [comment]
Thanks. The size of it never even crossed my mind. It's 553 KB now.
