### ISSUE TITLE
A Better Git Log Widget

### ISSUE THREAD

**Issue by adamdehaven** [felixhageloh/uebersicht-widgets#210]
https://github.com/adamdehaven/ubersicht-better-git-log

I took an existing widget idea and updated it with more configurable options, and made it "prettier" with better styling, "recent commit" colors, draggable, etc.

**Comment by soberstadt** [comment]
Hi, those look like really nice enhancements. Often times we encourage contributors to work together to make great widgets together. Are your changes at all mergeable with @DigitallyBorn's widget?

**Comment by adamdehaven** [comment]
I'm not sure if he'd want to merge the changes, however yes, it is basically a more enhanced version of his project. The basic idea is the same, but there are more variables, different layout, etc.

**Comment by felixhageloh** [comment]
I also like the enhancements! I would echo @soberstadt's sentiment tho to first check with @DigitallyBorn if he wants to merge in your improvements (or add you as a maintainer etc). This way we avoid having a Git Log Widget, a Better Git Log Widget, a Better Better Git Log Widget etc :)

**Comment by adamdehaven** [comment]
I sent @DigitallyBorn a pull request...

**Comment by DigitallyBorn** [comment]
And accepted! Latest commit is 1c93fe267e4270c499fa9c72b3ed5cf9ee2d1dc1.

(Thanks, @adamdehaven. I love it!)

**Comment by adamdehaven** [comment]
Update: Projects have been merged and enhanced. Be sure you have the latest version 2.0.1

**Comment by felixhageloh** [comment]
awesome, I will close this ticket then :)
