### ISSUE TITLE
SideBar.widget

### ISSUE THREAD

**Issue by avansteenbruggen** [felixhageloh/uebersicht-widgets#211]
Hey,

Made a collection of existing widgets (changed and created some of my own)

Hope you will add them to the page

https://github.com/avansteenbruggen/SideBar.widget

**Comment by felixhageloh** [comment]
Hey thanks for sharing and sorry for the late reply! At the moment I'm not adding collections of pre-existing widgets to the gallery (mostly because I'm unsure how to handle them). If you want to submit your own widgets individually, I'll be glad to add those!

**Comment by avansteenbruggen** [comment]
that's a shame :(
I really put in some time to get a good working collection.
Well, the github stays, if you want it you know where to get it.

thanks for making a super app :)
