### ISSUE TITLE
welcome.widget

### ISSUE THREAD

**Issue by roach0123** [felixhageloh/uebersicht-widgets#212]
https://github.com/roach0123/welcomewidget
Shows current time and user greeting for current logged in user.

**Comment by felixhageloh** [comment]
Thanks, I've added it!

**Comment by felixhageloh** [comment]
Sorry, my bad: I just realized that there was a widget essentially doing the same thing already: http://tracesof.net/uebersicht-widgets/#morning

Do you feel like your widget adds anything new that the existing one doesn't have? If not I would like to keep only the original one to not have duplicate widgets in the widget gallery.

Sorry again

**Comment by imRohan** [comment]
Any update on this 

@roach0123

**Comment by felixhageloh** [comment]
I will remove this widget for now. No bad intentions, just avoiding duplicates! @roach0123 let me know if you feel like this was unjust!
