### ISSUE TITLE
fuzzytime.widget

### ISSUE THREAD

**Issue by plan8studios** [felixhageloh/uebersicht-widgets#213]
I created a fuzzytime widget :-)

https://github.com/plan8studios/fuzzytime

**Comment by felixhageloh** [comment]
thanks for sharing! I think the only thing that is missing is a zip file containing the widget - you can check the [readme](https://github.com/felixhageloh/uebersicht-widgets#readme) for more details

**Comment by plan8studios** [comment]
Oops!! It's in there now :-)

**Comment by felixhageloh** [comment]
all good now, I've added it!
