### ISSUE TITLE
background.widget - Background Wallpaper pulled from Bing's photo of the day

### ISSUE THREAD

**Issue by roach0123** [felixhageloh/uebersicht-widgets#217]
https://github.com/roach0123/backgroundwidget

This widget will pull daily wallpaper from Bing's photo of the day API and add a fade to black at the bottom of the screen so you can add other widgets allowing them to be easily visable with a white font.

**Comment by felixhageloh** [comment]
Thanks for sharing - the fade to black on the bottom is a nice touch! I've added it
