### ISSUE TITLE
Duplicate Widgets?

### ISSUE THREAD

**Issue by imRohan** [felixhageloh/uebersicht-widgets#219]
This widget posted a week ago: 

http://tracesof.net/uebersicht-widgets/#welcomewidget

Is oddly similar to mine which was posted a few months ago 

http://tracesof.net/uebersicht-widgets/#morning

Even the code is similar...weird.

**Comment by felixhageloh** [comment]
My bad! I remember that there was a similar widget, but when I looked for something 'welcome' or 'greeting' I couldn't find anything. I will ping the author of the new widget

**Comment by felixhageloh** [comment]
still no answer but you can follow what's happening here https://github.com/felixhageloh/uebersicht-widgets/issues/212

**Comment by imRohan** [comment]
Thanks Felix for looking into it.

Will follow issue #212 :)
