### ISSUE TITLE
err running command in inspirational-quote widget

### ISSUE THREAD

**Issue by FantasRu** [felixhageloh/uebersicht-widgets#220]
Excuse me,i need an agent to visit feedburner.Why this does not work.

`command: 'export ALL_PROXY=socks5://127.0.0.1:1080 | curl -s "http://feeds.feedburner.com/brainyquote/QUOTEBR"' `

**Comment by felixhageloh** [comment]
I guess the issue is the proxy. Have you tried:

``` cofffeescript
command: 'curl --proxy socks5://127.0.0.1:1080 -s http://feeds.feedburner.com/brainyquote/QUOTEBR'
```

**Comment by FantasRu** [comment]
Thanks.It work.
