### ISSUE TITLE
Forecast Widget

### ISSUE THREAD

**Issue by uPaymeiFixit** [felixhageloh/uebersicht-widgets#221]
https://github.com/uPaymeiFixit/forecast-widget/tree/release
Uses Forecast.io API to show a 7 day forecast and current weather.

**Comment by felixhageloh** [comment]
Thanks for sharing, it looks great!
I didn't check in detail, but it does look like it is very similar to the existing weather widget. Would it be an idea to add your styling improvements as an option to the original weather widget?

**Comment by uPaymeiFixit** [comment]
There are a few weather widgets on your site. Which one are you referring to?

If so, I think the only way to include the styling improvements would be to completely replace the original weather widget, at which point you might rather just include them both in order to give users more options. I personally like all of the weather widgets on your site and feel they each provide something slightly unique.

**Comment by felixhageloh** [comment]
I was referring to this one http://tracesof.net/uebersicht-widgets/#weather, but looking at yours again, I guess there are enough differences to add it as a separate widget (it is a hard line to walk sometimes :) )

**Comment by felixhageloh** [comment]
The only thing missing is the zip file needs to be in the root of the repo (the build script expects it there) - then I can add it!

**Comment by uPaymeiFixit** [comment]
Does [forecast.widget.zip](https://github.com/uPaymeiFixit/forecast-widget/blob/release/forecast.widget.zip) need to be in the root directory of the [master branch](https://github.com/uPaymeiFixit/forecast-widget/tree/master), or is it okay in the root directory of the [release branch](https://github.com/uPaymeiFixit/forecast-widget/tree/release)?

**Comment by felixhageloh** [comment]
Currently the script only works with the master branch

**Comment by dudeofawesome** [comment]
Where is the script? Maybe I can update it to work with other branches so that peoples' master branches don't have to get clogged up with release files.

**Comment by uPaymeiFixit** [comment]
I have uploaded forecast.widget.zip to the master branch.

**Comment by felixhageloh** [comment]
sorry for the late response!
@dudeofawesome @uPaymeiFixit is it a common pattern to have a separate branch for builds/releases (I never came across it)? I'm not against adding it to the script if that's the case, but I'd like to keep it simple, which means not necessarily supporting all different repo layouts. 

@uPaymeiFixit great, I've added it!
