### ISSUE TITLE
Binary Clock Widget

### ISSUE THREAD

**Issue by jeisner93** [felixhageloh/uebersicht-widgets#223]
Hey, felixhageloh:

I just wrote my first widget; a binary clock widget that supports both 12 and 24 hour formats with a simple change to the index.coffee. I would love to see it up in the widget gallery! Let me know what you think.

The URL to it is here: https://github.com/jeisner93/ubersicht-binary-clock

Thanks,
Joel

**Comment by felixhageloh** [comment]
Looks nice, although I'd have to practice a bit to be able to read the time :D. Thanks, I've added it!

**Comment by jeisner93** [comment]
Thanks for adding it! And yeah, being able to read it does take a bit of practice!
