### ISSUE TITLE
How is command execution done?

### ISSUE THREAD

**Issue by roele** [felixhageloh/uebersicht-widgets#226]
@felixhageloh How does Übersicht spawn the shell to execute the `command`? I noticed some issues with my shell script referenced in `command` not honoring the PATH variable.

**Comment by felixhageloh** [comment]
It uses NodeJS' `spawn`

```
{spawn} = require('child_process')
shell = spawn 'bash', [], cwd: workingDir
```

Passing on env variables would be handy, but I haven't had time to look into it yet
