### ISSUE TITLE
Widget for coding.net notifications

### ISSUE THREAD

**Issue by IUsual** [felixhageloh/uebersicht-widgets#227]
I make a widget [here](https://github.com/IUsual/coding-net-notifications.widget)，so would you like take a glance and include it in the gallery?

**Comment by felixhageloh** [comment]
thanks for sharing! It is in the gallery now!

**Comment by IUsual** [comment]
@felixhageloh However, it appears that the widget has been remove from gallery now, I had saw it two days before.

**Comment by felixhageloh** [comment]
you are right, sorry my bad! 
I had an un-pushed commit locally and someone one else updated the widget gallery. It is fixed now!

**Comment by IUsual** [comment]
Thanks a lot!
