### ISSUE TITLE
Minimal Forecast Widget

### ISSUE THREAD

**Issue by cpmsmith** [felixhageloh/uebersicht-widgets#228]
I've written [a widget](/cpmsmith/minimal-forecast-widget) to show temperature trends in a very reserved way:

![Widget](https://raw.githubusercontent.com/cpmsmith/minimal-forecast-widget/master/screenshot.png)

Consider adding it?

**Comment by soberstadt** [comment]
Wow, this looks really slick! Have you thought about how this might work for areas that don't get down to 0 ever? I'm in Florida, USA and I'm trying to think how some context could show what the bars mean.

**Comment by cpmsmith** [comment]
@soberstadt I'm thinking of adding grid lines every few degrees—maybe 5°C and 10°F—for more context. It's definitely influenced by Ottawa winter at the moment.

**Comment by soberstadt** [comment]
What if you added those dashed lines every 5/10 and then had 0 be either solid or a different color?

**Comment by cpmsmith** [comment]
That's just what I had in mind, so I've added it. I found there's less cognitive overhead when it's every 10, but I left it configurable.

**Comment by soberstadt** [comment]
Sorry for the delay, you should see it up there now! Great widget, it has found a home on my desktop!
