### ISSUE TITLE
New Mail Widget

### ISSUE THREAD

**Issue by roadglide03** [felixhageloh/uebersicht-widgets#230]
Shows count and from plus subject.  See:

https://github.com/roadglide03/mail-count-read.widget.git

**Comment by felixhageloh** [comment]
Similar your other request: Please make sure you have a 'main screenshot' file called screenshot.png  You can include extra screenshots inside the readme of your widget!

**Comment by roadglide03** [comment]
Ok done thanks Andy

**Comment by roadglide03** [comment]
Ok done thanks Andy

**Comment by felixhageloh** [comment]
sorry, I think you have a typo sceenshot ->  screenshot 
<img width="251" alt="screen shot 2016-03-10 at 18 01 11" src="https://cloud.githubusercontent.com/assets/367503/13677414/31591804-e6ea-11e5-8311-4e77cdf9bed7.png">

**Comment by roadglide03** [comment]
should be good now

**Comment by felixhageloh** [comment]
Made a PR to fix the final incorrect quotes!

**Comment by roadglide03** [comment]
Okay I fix the quotes for both of them should be good now.  thanks Andy

**Comment by felixhageloh** [comment]
all good now, i've added it!
