### ISSUE TITLE
New VM Display Widget

### ISSUE THREAD

**Issue by roadglide03** [felixhageloh/uebersicht-widgets#231]
Displays the count of running virtual machines from Fusion, Parallels, and Virtual Box.  Also displays VM name if running.  Only configuration is changing the path to your VM application if different than default. Comment out any VM lines that are not required. 

https://github.com/roadglide03/vms.widget.git

**Comment by felixhageloh** [comment]
Thanks for sharing! Can you make sure you have a 'main screenshot' file called screenshot.png (or .jpg etc)? You can include extra screenshots inside the readme of your widget!

**Comment by roadglide03** [comment]
Ok done

**Comment by felixhageloh** [comment]
sorry about this but I still get an error from the build script:
<img width="329" alt="screen shot 2016-03-10 at 18 02 50" src="https://cloud.githubusercontent.com/assets/367503/13677449/556d5e1c-e6ea-11e5-955a-d21ad60f1c0c.png">

It could be that you saved the manifest file using TextEdit. Unfortunately it switches regular quotes `"` to `“`

**Comment by roadglide03** [comment]
should be good now

**Comment by felixhageloh** [comment]
there were still a few incorrect quotes - I made a PR to fix them!

**Comment by felixhageloh** [comment]
added it!
