### ISSUE TITLE
New Network Throughput Monitor Widget

### ISSUE THREAD

**Issue by dionmunk** [felixhageloh/uebersicht-widgets#232]
A simple network throughput monitor to match some of the other available widgets.

https://github.com/dionmunk/ubersicht-network-throughput

**Comment by felixhageloh** [comment]
Thanks I've added it! 

I noticed that there is already a very similar widget in the gallery. @agileadam are you ok with this or would you rather collaborate and merge in @dionmunk's style improvements?

**Comment by agileadam** [comment]
dionmunk's definitely looks sharper! Nice work.

felix, if you only want to have one around, feel free to make the call however you see fit.
If you don't mind having both I'd just leave them as-is.

**Comment by dionmunk** [comment]
@felixhageloh @agileadam 
I'm fine either way. I just wanted to make this available. Thanks!

I have a few more that match that I will release soon.

**Comment by felixhageloh** [comment]
cool guys, I'll leave it as is for now!
