### ISSUE TITLE
Strava progress tracker

### ISSUE THREAD

**Issue by Pe8er** [felixhageloh/uebersicht-widgets#233]
I made a thing! This widget grabs your weekly and yearly biking stats from Strava and displays them in a somewhat visual manner.

![](http://imgur.com/SshwpoP.jpg)

https://github.com/Pe8er/Strava.widget

**Comment by felixhageloh** [comment]
looks great as usual :). I've added it!
Also haven't forgotten about your mockups - just haven't done much development on Übersicht that touches the UI since
