### ISSUE TITLE
Simple Machine/Peripheral Stats

### ISSUE THREAD

**Issue by Paradiddley** [felixhageloh/uebersicht-widgets#235]
A collection of really simple machine stats.

https://github.com/Paradiddley/Simple-Uber-Stats

**Comment by felixhageloh** [comment]
Hey thanks for sharing - looks like some nice widgets! Unfortunately the current gallery setup doesn't allow for repos with several widgets. If you could create a repo per widget then I can add them

**Comment by Paradiddley** [comment]
Ah, sorry about that. I hope these now meet the requirements. Also, thank you!

https://github.com/Paradiddley/Simple-Uber-System-Status
https://github.com/Paradiddley/Simple-Uber-Device-Status
https://github.com/Paradiddley/Simple-Uber-Disk-Usage

**Comment by felixhageloh** [comment]
perfect, thanks - I've added them as well!

**Comment by Paradiddley** [comment]
Awesome, thank you!
