### ISSUE TITLE
Request to integrate simpledate widget

### ISSUE THREAD

**Issue by ruurd** [felixhageloh/uebersicht-widgets#237]
Following the discussion in #234, please integrate this widget.

https://github.com/ruurd/simpledate

If additional polish is necessary I would be happy to oblige.

**Comment by felixhageloh** [comment]
Cool - I'd only ask you to pick a different name since simpledate is already taken (well, SimpleDate, but close enough)

**Comment by ruurd** [comment]
JustTheDate.widget then?

**Comment by felixhageloh** [comment]
works for me :)! You can just notify me here when you changed the name

**Comment by ruurd** [comment]
When you're ready. Say. Felix. Are you still working in Amsterdam?

**Comment by felixhageloh** [comment]
great, I've added it! And yes I do still work in Amsterdam :)
