### ISSUE TITLE
New Widget: Xiami FM Widget

### ISSUE THREAD

**Issue by ProfFan** [felixhageloh/uebersicht-widgets#238]
URL: https://github.com/ProfFan/Ubersicht-XiamiFM

This is a widget for a popular music service in China :)

**Comment by felixhageloh** [comment]
Thanks for sharing! Can you also make sure to include a zip file and widget manifest in your repo (https://github.com/felixhageloh/uebersicht-widgets#readme) - then I can add it

**Comment by ProfFan** [comment]
Fixed :)

**Comment by felixhageloh** [comment]
thanks, I've added it!
