### ISSUE TITLE
Updated widget

### ISSUE THREAD

**Issue by justiceamoh** [felixhageloh/uebersicht-widgets#240]
Hi Felix, I fixed a bug in my original widget:
[https://github.com/justiceamoh/DailyBibleVerse](https://github.com/justiceamoh/DailyBibleVerse). 
What is the best way to effect the update on your repo? Thanks.

~ justice

**Comment by felixhageloh** [comment]
HI there! Since the widget is in your own repo it will update automatically once you update your zip file - or actually better to say: the widget gallery links to your repo so people are downloading it directly from there
