### ISSUE TITLE
New widget: moon-phase

### ISSUE THREAD

**Issue by joecreighton** [felixhageloh/uebersicht-widgets#241]
I think it's ready.

https://github.com/joecreighton/moon-phase

**Comment by felixhageloh** [comment]
Great, looks good!
When running the build script for the gallery I came across a trailing coma in your widget manifest (widget.json). Unfortunately, JSON is strict about trailing commas, so if you fix that I can add your widget!

**Comment by joecreighton** [comment]
Done.

**Comment by felixhageloh** [comment]
all checks out now, thanks - I've added it!

**Comment by joecreighton** [comment]
Yay! My first "thing!" :)
