### ISSUE TITLE
Request for the gallery: accept JPG screenshots

### ISSUE THREAD

**Issue by Pe8er** [felixhageloh/uebersicht-widgets#242]
Hey,

I've added retina widget screenshots to my repos, but they don't show up in Widget gallery. Probable reason: I'm using JPGs instead of PNGs. I'm doing that because downscaled retina JPG looks as good as a PNG but is a lot lighter.

Is there a chance you could modify the gallery so it accepts JPG screenshots too?

**Comment by felixhageloh** [comment]
At the moment I'm not supporting different screenshots for retina and non retina, but if you make your screenshot 516x320px it will be retina ready and it should still look decent on non-retina screens. (basically, I'm scaling all images to half that (258x160px)). Not sure if I explained that well, so let me know if it makes any sense :)

**Comment by Pe8er** [comment]
I understand everything, it's just that due to severe brain damage caused by years of doing design, I can't agree with

> should still look decent on non-retina screens

😄 It's definitely not high priority, although I hope you can implement at some point in the future. I'll make do in the meantime, no worries!
