### ISSUE TITLE
New widget for the gallery: put.io TV Shows viewer

### ISSUE THREAD

**Issue by gitzerai** [felixhageloh/uebersicht-widgets#243]
Have info about your latest TV Shows downloaded from put.io service right on your Mac desktop.

Widget gallery files: https://github.com/gitzerai/ubersicht-putio/tree/master/release/1.0

**Comment by felixhageloh** [comment]
Hey thanks for sharing you widget! 
Unfortunately the gallery build script won't be able to parse your repo layout - the release files should be in the root of the repo. If you could change that then I can add it!

**Comment by gitzerai** [comment]
Alright, not a problem - moved to root folder.

**Comment by felixhageloh** [comment]
great! I've added it

**Comment by gitzerai** [comment]
Awesome, thanks!

BTW - Kudos to the entire Ubersicht project, love it from the start 👍
