### ISSUE TITLE
ip.appspot.com service not working.

### ISSUE THREAD

**Issue by agustif** [felixhageloh/uebersicht-widgets#244]
I could get the widget to work by changing the url to this one i found on the net: http://ipinfo.io/ip

same command and curl -opts.

**Comment by felixhageloh** [comment]
which widget is this referring to?

**Comment by felixhageloh** [comment]
closing for now

**Comment by agustif** [comment]
Im so sorry, I never got back to you with an answer, it was this: https://github.com/felixhageloh/uebersicht-widgets/blob/master/public_ip/public_ip.widget/index.coffee

Sorry again for missing it!

**Comment by felixhageloh** [comment]
ok no worries :)! I checked it again and it seemed to work. Maybe ip.appspot.com was down temporarily
