### ISSUE TITLE
New version of justthedate without the @style issue

### ISSUE THREAD

**Issue by ruurd** [felixhageloh/uebersicht-widgets#245]
Hey Felix, 

Can you pick up my update to justthedate? I changed it to prevent the @style problems.
https://github.com/ruurd/justthedate#master

**Comment by felixhageloh** [comment]
If you update the zip in your repo the update will get picked up automatically!

**Comment by ruurd** [comment]
I did that too :-) So yes it should be picked up :-)

**Comment by felixhageloh** [comment]
ok great, let me know if you don't see the update coming in for some reason :)

**Comment by ruurd** [comment]
Boy you're fast.
Waar hang je overigens in Amsterdam? (Zit bij ING vlakbij station ArenA)

**Comment by felixhageloh** [comment]
Haha :), bij https://www.publitas.com dicht bij het Brouwerij 't IJ

**Comment by ruurd** [comment]
Oh ja dat is ook zo. Zeeburgerpad. Heb ooit eens een sollicitatie gedaan bij jullie. Overigens laatst een IPA gedronken van 't IJ. Lekker. Zit je goed daar :-)

**Comment by felixhageloh** [comment]
Ja hoor! Ik hou meestal niet zo van de IJ bieren, maar de IPA is wel lekker :)
(switching to english because my written dutch is very poor)
So you applied for a position by Publitas once - when was that?

**Comment by ruurd** [comment]
I think somewhere mid 2013... Have to look it up.
