### ISSUE TITLE
Github Contributions (possible dupe)

### ISSUE THREAD

**Issue by eanplatter** [felixhageloh/uebersicht-widgets#246]
Hi @felixhageloh great platform!

I know you've mentioned not wanting duplicate widgets on the site, that being said this isn't a fork of the current github contributions widget, but rather a rewrite: https://github.com/eanplatter/minimal-github-widgit

The current github contributions widget on the site is broken, and has been for almost 2 years. Last year someone made a PR on the broken widget to fix it, but there wasn't a response: https://github.com/cobyism/ubersicht-github/pull/6

Someone else wrote a rewrite about 18 months ago, but he was encouraged to instead make a PR to fix the current widget on the site: https://github.com/felixhageloh/uebersicht-widgets/issues/89

I think it's been long enough to consider removing the old widget in exchange for a new one. I've also added rotation and dragging functionality to it 😀 what else could the world want.

**Comment by felixhageloh** [comment]
you make a very strong case :)
I've added your widget and removed the old github contributions widget!

**Comment by eanplatter** [comment]
😃😃😃 thanks!
