### ISSUE TITLE
Aoede widget

### ISSUE THREAD

**Issue by pyraxo** [felixhageloh/uebersicht-widgets#247]
yet another current-playing widget. it may be my first widget, but before i knew it there were tons that were similar. i hope i still can submit mine either way! i designed it after the monstercat videos

https://github.com/pyraxo/aoede

**Comment by felixhageloh** [comment]
Hey thanks for sharing! There are indeed already a few now playing widgets - this doesn't seem like a copy with a few tweaks tho, so I've added it!
