### ISSUE TITLE
air-quality.widget

### ISSUE THREAD

**Issue by FanZhen2002** [felixhageloh/uebersicht-widgets#248]
Air quality index (AQI) widget for Übersicht.
Show AQI data from aqicn.org.

https://github.com/FanZhen2002/air-quality.widget

**Comment by felixhageloh** [comment]
thanks for sharing! Please make sure to add zip file for your widget to your repo so I can add it to the gallery

**Comment by FanZhen2002** [comment]
zip file added.

**Comment by felixhageloh** [comment]
thanks, I've added it! Sorry for the late reply - my son was born last week :)
