### ISSUE TITLE
Time Since widget

### ISSUE THREAD

**Issue by johnmathews** [felixhageloh/uebersicht-widgets#249]
'Time Since...' widget for Übersicht.

Shows the months, days, hours and minutes since a date and time specified, with optional text before and after.

https://github.com/johnmathews/time_since

**Comment by johnmathews** [comment]
Second commit adds seconds to the counter, and improves the structure of the widget.

**Comment by felixhageloh** [comment]
thanks and sorry for the late reply! I've added it!
