### ISSUE TITLE
UpcomingEvents

### ISSUE THREAD

**Issue by cbeardsmore** [felixhageloh/uebersicht-widgets#251]
Lists upcoming events from iCalender using icalBuddy.
There are similiar widgets out there, but none with the styling or as finished as this I found.

https://github.com/cbeardsmore/UpcomingEvents

**Comment by felixhageloh** [comment]
hey thanks for sharing (and sorry for the late reply)! Just to double check, the difference with this widget http://localhost:3030/#gcal-widget is that it shows iCal events instead of google calendar?

**Comment by cbeardsmore** [comment]
no worries! :) yes, this syncs straight from your iCal events. i don't use gcal much so i wanted something just for iCal!

**Comment by felixhageloh** [comment]
sorry again for the late reply - as you might have heard/seen, my son was born a few weeks ago, so I don't get to a lot of Übersicht stuff :).

So about the widget: maybe you could rename it to 'Upcoming iCal Events' or something, to make it clear what distinguishes it from the other similar widgets. I'd be happy to add it to the gallery then

**Comment by cbeardsmore** [comment]
congratulations! all the best for the little one :)

I've renamed the widget to "Upcoming-iCal-Events" and made the README a little clearer about how it's different from the others! thankyou

**Comment by felixhageloh** [comment]
Thanks :)!!

It looks good now, except you also need to change the name inside widget.json (because that's what will be shown in the gallery)

**Comment by cbeardsmore** [comment]
oops! i knew i forgot something. fixed now

**Comment by felixhageloh** [comment]
awesome, I've added it!
