### ISSUE TITLE
WiFi Tx Speed Widget

### ISSUE THREAD

**Issue by mactexan** [felixhageloh/uebersicht-widgets#254]
Created a simple little widget to collect and display the actual transmission speed of your WiFi connection.
![wifi_tx](https://cloud.githubusercontent.com/assets/2218604/17085192/edc8d30e-5197-11e6-9b91-e3139ba2758e.png)

**Comment by felixhageloh** [comment]
Thanks for sharing! Could you rename your screenshot from `WiFi_Tx.png` to `screenshot.png` - that way the automatic build script can pick it up.

**Comment by mactexan** [comment]
All done.
Thanks,
Joe Kelley

**Comment by felixhageloh** [comment]
thanks, I've added it!
