### ISSUE TITLE
kaspersky-threats

### ISSUE THREAD

**Issue by mactexan** [felixhageloh/uebersicht-widgets#255]
New widget to view Kaspersky's real-time cyberthreat animated globe.

**Comment by mactexan** [comment]
This is a widget I put together to display kaspersky's animated real-time cyberthreat globe. It is re-sizeable by changing the value of the data-width and data-height tags within the render script. Don't know how useful it is, but it's fun to look at.
![screenshot](https://cloud.githubusercontent.com/assets/2218604/17161212/4898b8fa-5371-11e6-8993-9504194d89a9.png)

**Comment by felixhageloh** [comment]
Looks neat, thanks again! I've added it
