### ISSUE TITLE
application menu

### ISSUE THREAD

**Issue by fokstune** [felixhageloh/uebersicht-widgets#256]
I'm really a newbie here.
Any chance to see a script to add the application menu? Just to totally customize the status bar.
In other way, Is that possible? Just to know.

**Comment by felixhageloh** [comment]
If I understand you correctly, you would like to use Übersicht to customize the status bar? Or would you like to customize the Übersicht icon in the status bar?

**Comment by fokstune** [comment]
Yes. I'm not very explicit, sorry.
I use  [nerdbar.widget](https://github.com/herrbischoff/nerdbar.widget) and actualy the menu bar is hidden.
Project is to replace the menu bar by a widget for total custom.
It's possible for me to customize existing widget to replace date, time and some iStat feature but I don't know how can I reproduce application menu. And I don't know If it's possible too.

**Comment by felixhageloh** [comment]
Oh I see, thanks for clarifying. There is also this widget which also shows the current active app http://tracesof.net/uebersicht-widgets/#bar, but I think recreating the entire application menu will be difficult, if not impossible to do

**Comment by felixhageloh** [comment]
(closing this given that it is a question)
