### ISSUE TITLE
Git branches for list of folders

### ISSUE THREAD

**Issue by synle** [felixhageloh/uebersicht-widgets#259]
**ubersichtGitInfo**
Allow you to track a list of folders stored in your local machines and their current branches

<img width="279" alt="1" src="https://cloud.githubusercontent.com/assets/3792401/17633697/72936bc2-6083-11e6-9628-7e066afb8c54.png">

**Comment by felixhageloh** [comment]
Hi, thanks for sharing and sorry for the late reply! Can you provide a link to the widget repo so I can add it :)?

**Comment by synle** [comment]
@felixhageloh 

This is the link to my repo: https://github.com/synle/ubersichtGitInfo

Also I dropped the dependencies on node and now the code should work with pure bash shell command.

**Comment by felixhageloh** [comment]
thanks! Can you also make sure to include a screenshot (called screenshot.png) and a zip file containing your widget - that way the automatic build script can pick it up. Details can be found in the readme!

**Comment by synle** [comment]
Thanks, @felixhageloh. I added all the required files. Let me know if I need to add anything else

![screen shot 2016-08-31 at 10 58 17 am](https://cloud.githubusercontent.com/assets/3792401/18140328/e7c70288-6f69-11e6-916e-c8019e1cfd2b.png)

**Comment by felixhageloh** [comment]
great! All good now, I've added it
