### ISSUE TITLE
Sensu events widget

### ISSUE THREAD

**Issue by GhostLyrics** [felixhageloh/uebersicht-widgets#262]
As discussed on Twitter.

https://github.com/GhostLyrics/uebersicht-sensu/tree/master

**Comment by felixhageloh** [comment]
Thanks! Can you also add a screenshot.png and widget.zip file to your repo (details are in the README) - that way the automatic build script for the gallery can pick it up.

**Comment by GhostLyrics** [comment]
Done as of commit https://github.com/GhostLyrics/uebersicht-sensu/commit/1ddbcc8e48aa7d74b40c6f31415ad4a6acf31dcf.

**Comment by felixhageloh** [comment]
Thanks! Almost there now: can make sure the screenshot is named `screenshot.png|jpg`?

**Comment by GhostLyrics** [comment]
I'm sorry you have to babysit this. May I suggest writing a little spec helper or something that can check if a repo fits the requirements?

Anyway, done with https://github.com/GhostLyrics/uebersicht-sensu/commit/4b6445ff936280d32ce0cc8ec425059f97b77bd9.

**Comment by felixhageloh** [comment]
no worries - yeah a git repo validator would be handy but I haven't gotten around to it yet. 
So there is one last issue: I noticed that your are using git lfs, so images are not showing in the gallery (i'd have to build in support for git lfs I guess). Is there a chance you can switch at least the screenshot to s standard image?
For the images inside your readme, you could also just drag&drop them in the github interface - that way you don't have to store them in your repo

**Comment by GhostLyrics** [comment]
Took a while, but should be according to your spec now.

**Comment by felixhageloh** [comment]
Thanks almost there - I think only the zip file is missing now!

**Comment by GhostLyrics** [comment]
Added. Still think it would better fit in github releases, but okay :)

**Comment by felixhageloh** [comment]
forgot to mention here - it has been added :)
