### ISSUE TITLE
Sierra breaks Network Throughput widget

### ISSUE THREAD

**Issue by fishbiscuit13** [felixhageloh/uebersicht-widgets#266]
For whatever reason Sierra removed the sar command, which obviously breaks Network Throughput. Do you know of any other commands that you can pull throughput stats from?

**Comment by felixhageloh** [comment]
sorry for the late reply! I also looked around a bit and haven't found a replacement. There is a few people asking the same question in the developer forums but no answers so far. The best I have is https://github.com/rgcr/m-cli - maybe there is something in there that does the same

**Comment by fishbiscuit13** [comment]
No worries, thanks for looking into it! I'll check that out and see if I can make it work.
