### ISSUE TITLE
New Widgets Assembly

### ISSUE THREAD

**Issue by larousse96** [felixhageloh/uebersicht-widgets#268]
Hey,

I made quite a nice desktop here and i wanted to share it.
hope you like it

Lucas

https://github.com/larousse96/MyDesktopAssembly.git

**Comment by felixhageloh** [comment]
Hey, nice looking desktop! I don't really have a way to share widget sets on the gallery, but if you like I can send a tweet with your repo. I was thinking maybe you want to include the screenshot in your readme (so people can immediately see it) before I do so?

**Comment by larousse96** [comment]
there, done :) and yes i'd love so thanx :)

**Comment by felixhageloh** [comment]
done :)

**Comment by larousse96** [comment]
Thanx :)
