### ISSUE TITLE
network-throughput: macOSX sierra, command not working

### ISSUE THREAD

**Issue by abhivanarase** [felixhageloh/uebersicht-widgets#270]
The `sar` command seems to not work on mac osx sierra causing the command for the network-throughput widget to fail.

**Comment by felixhageloh** [comment]
closing this one as a duplicate

**Comment by felixhageloh** [comment]
The main discussion is on the other thread

**Comment by cartesis07** [comment]
Hi, for MAC OS users whose sar command does not work, I adapted the widget with this command using netstat :

command: "netstat -w1 -I en0 | head -3 | awk '{print $3,$6}' | tail -1"

You can replace it in the index.coffee file of the Network Throughput Übersicht widget. It is working pretty well and you can choose the refreshFrequency you prefer.
