### ISSUE TITLE
New Widget : Tsushin - Dynamically updating line chart that shows network throughput

### ISSUE THREAD

**Issue by louixs** [felixhageloh/uebersicht-widgets#275]
Hi! I'd like to submit a widget here.

Dynamically updating line chart that shows network throughput - heavily inspired by Dion Munk's network-throughput widget. 

Url: https://github.com/louixs/tsushin
Many thanks!

**Comment by felixhageloh** [comment]
thanks! I've finally added it - sorry for the delay

**Comment by louixs** [comment]
@felixhageloh No worries at all. Thanks a lot!

**Comment by louixs** [comment]
@felixhageloh hi again! Only now, I noticed that the name of the app on http://tracesof.net/uebersicht-widgets/ has one too many letter. It should be Tsushin and not Tshushin.. I checked REAME.md and codes in my repo but couldn't find where the typo might come from. Where is your /uebersicht-widgets page taking widget's titles from? If it's hardcoded, I'd be grateful if you could eventually correct it. Not urgent so no hurry though! 

Thanks.

**Comment by felixhageloh** [comment]
hey, it takes the name from the widget manifest file https://github.com/louixs/tsushin/blob/master/widget.json. Most changes will appear on the site automatically but I think a name change won't, so ping me once you've fixed the name and I will update the site

**Comment by louixs** [comment]
My bad @felixhageloh. Found a typo in the widget.json file and corrected it now. Many thanks!

**Comment by felixhageloh** [comment]
alright, great! I've updated the site
