### ISSUE TITLE
WiFi SSID Widget

### ISSUE THREAD

**Issue by mactexan** [felixhageloh/uebersicht-widgets#276]
This little widget displays the name of the currently connected WiFi network. I could be useful in an environment where there are multiple networks available.
[WiFi-SSID-Widget.zip](https://github.com/felixhageloh/uebersicht-widgets/files/559520/WiFi-SSID-Widget.zip)

**Comment by felixhageloh** [comment]
thanks for sharing and sorry for the delay! If I am not mistaken, this one is already in the gallery http://tracesof.net/uebersicht-widgets/#WiFi-Tx-Speed!

**Comment by mactexan** [comment]
This one’s a bit different. This one displays the wifi network name. The WiFi-Tx-Speed displays the wifi connection tx rate. I did make the SSID widget by modifying the tx-speed widget I wrote.

**Comment by felixhageloh** [comment]
Oh sorry my bad! Do you have a repo for this widget? (the gallery currently only works for GitHub repos)

**Comment by mactexan** [comment]
Sorry, that was my bad.

https://github.com/mactexan/WiFi-SSID-Widget <https://github.com/mactexan/WiFi-SSID-Widget>


thx

**Comment by felixhageloh** [comment]
thanks! Almost there - could you also add the zip file to your repo?

**Comment by felixhageloh** [comment]
thanks I've added it!
