### ISSUE TITLE
Getting Ubersicht error when trying to change stocks on Simple Stocks

### ISSUE THREAD

**Issue by bradwolff18** [felixhageloh/uebersicht-widgets#277]
<img width="346" alt="screen shot 2016-11-02 at 9 25 38 am" src="https://cloud.githubusercontent.com/assets/23216189/19932492/5b4e4f04-a0de-11e6-9a75-cd3aafe45723.png">

**Comment by felixhageloh** [comment]
you have a syntax error in you widget somewhere ... hard to say were without seeing the code tho

**Comment by felixhageloh** [comment]
(closing this issue but feel free to follow up)
