### ISSUE TITLE
Black Bar Widget

### ISSUE THREAD

**Issue by jrb12364** [felixhageloh/uebersicht-widgets#279]
https://github.com/jrb12364/Black-Bar-Widget

**Comment by felixhageloh** [comment]
thanks, I've added it! How does this work btw?

**Comment by jrb12364** [comment]
This is more of a slight aesthetic fix rather than some of the other übersicht widgets. I basically noticed that macOS leaves a slight 5px high border on the bottom of the window to allow for selection of the dock. If you have a light background on a dark window, it causes an annoying look, which this widget fixes by putting a black bar over it.

**Comment by felixhageloh** [comment]
oh ok - your new screenshot also shows it more clearly. Thanks for explaining :)
