### ISSUE TITLE
Commandment-11

### ISSUE THREAD

**Issue by cscharff** [felixhageloh/uebersicht-widgets#280]
Created a widget to display the 11th commandment as part of a One Time Pad. 

https://github.com/cscharff/commandment-11

I borrowed heavily from the wordclock widget. I changed it enough that it's no longer really a clock... In the future I hope to be able to dynamically create the OTP and make some of the highlighting more dynamic in keeping with the cryptographical spirit of the widget itself.

**Comment by felixhageloh** [comment]
Thanks for sharing! Can you also add a screenshot to your repo so I can add it to the gallery?
What is the 11th commandment btw :)?

**Comment by cscharff** [comment]
Added the screenshot. :) 

The 11th commandment is "Thou shalt not get caught".

Working on a couple of other widgets now.

**Comment by felixhageloh** [comment]
oh I see :). All goo now, I've added it!
