### ISSUE TITLE
Smooth Analog Clock

### ISSUE THREAD

**Issue by N00bySumairu** [felixhageloh/uebersicht-widgets#281]
First off I'd like to express my thanks for Übersicht, I've really enjoyed working with it so far (I migrated from GeekTool).

I created an [analog clock widget](https://github.com/N00bySumairu/SmoothAnalogClock.widget) with pointers turning at a constant speed. It runs using css transitions of the transform property of the pointers, allowing it to be hardware accelerated. This fact enables the clock to potentially run silky smooth animations at 60fps and also reasonably efficient (the WebKit process hasn't exeeded 2% CPU usage for me yet).
I thought I'd share it, as I haven't come across something similar yet.

If anything is off about the widget setup please tell me, I'll try to fix it.

**Comment by felixhageloh** [comment]
Thanks, glad you enjoy the app :). I've added your widget! There are a few analog clocks already but I am not sure if any of them makes use of hardware acceleration
