### ISSUE TITLE
Noob Alert

### ISSUE THREAD

**Issue by xxspartacusxx** [felixhageloh/uebersicht-widgets#282]
Hello,

I downloaded and installed the widget, however, I am not even slightly sure how to add tasks to the list. Upon installation, I get a line of text on my desktop saying:

cat: /Volumes/Macintosh HD/ToDo.list: No such file or directory

Please excuse my lack of experience,
Thank you for your help in advance :)

**Comment by felixhageloh** [comment]
Hi, I'm assuming it is about this widget http://tracesof.net/uebersicht-widgets/#to-do-list
I see there is no readme available, but from looking at the code it looks like it expects a file called ToDo.list at the path you mentioned. You can change it in the widget by editing line 6

```copfescript
todolistfile = '~/ToDo.list'
```

to whatever path you like. There is also a comment on how to manage todo list items:
```
# ToDoList Entries:
# Use a '-' for an open item
# Use a '+' for a completed item
```

I hope this helps!

**Comment by felixhageloh** [comment]
closing this issue for now, but feel free to follow up with questions here!

**Comment by xxspartacusxx** [comment]
Thank you Felix, it works now!

Cheers!
