### ISSUE TITLE
Simple widget for check and show Comcast data usage.

### ISSUE THREAD

**Issue by aplsms** [felixhageloh/uebersicht-widgets#283]
Hello,

I have small widget for comcast data usage.
Please take a look: https://github.com/aplsms/ComcastUsage
I can prepare .zip file if you need it.

Thank you,
Andrii

**Comment by felixhageloh** [comment]
Hey, sorry for the late reply - quite swamped with work these days. The widget looks good, so if you want to add a zip file I can add it to the gallery :)!

**Comment by felixhageloh** [comment]
closing for now - let me know if/when you gave added a zip file!
