### ISSUE TITLE
No Native Nodejs Modules

### ISSUE THREAD

**Issue by Coderwelsch** [felixhageloh/uebersicht-widgets#284]
While writing a widget I mentioned that it is not possible to require native node modules like 'fs'. Other post installed modules like handlebars are working well and will not return an empty object {}. 

Not working:
let fs = require("fs"); // Returns an empty object

This is a bug, right?

Cheers
Joseph :)

**Comment by felixhageloh** [comment]
you can install some native modules, but only the ones that run inside a browser (which is what Üversicht essentially is). So `fs` is out, but here is a list of native modules you should be able to require https://github.com/substack/node-browserify#compatibility

However, you can make a js executable which you then  call using `command:` in which you can use fs

**Comment by Coderwelsch** [comment]
OK, thank you for your fast reply!

**Comment by felixhageloh** [comment]
glad I could help!
