### ISSUE TITLE
Simple widget to show holidays information

### ISSUE THREAD

**Issue by DiSiqueira** [felixhageloh/uebersicht-widgets#285]
Created a widget which shows wikipedia holidays information.
https://github.com/DiSiqueira/uebersicht-wiki-holidays.widget

preview: 
![image](https://cloud.githubusercontent.com/assets/683170/21470118/c8109dc0-ca61-11e6-8f8c-16875a98cbc0.png)

**Comment by felixhageloh** [comment]
hey thanks for sharing and happy holidays :)! I've added it to the gallery
