### ISSUE TITLE
New Widget : Gmail widget with Google Oauth2

### ISSUE THREAD

**Issue by louixs** [felixhageloh/uebersicht-widgets#287]
Hi @felixhageloh! It's me again. 

This time, I'm requesting to add a new and hopefully exciting widget, as a part of my google api widget series project. 

It's a widget that displays the sender and the subject line of the latest gmail in your inbox (so far).
URL: https://github.com/louixs/ubersicht_gmail

Thanks!

**Comment by felixhageloh** [comment]
as mentioned in the other issue: added it!
