### ISSUE TITLE
New Widget - Stravasicht Visualiser

### ISSUE THREAD

**Issue by draganmarjanovic** [felixhageloh/uebersicht-widgets#289]
Widget and more info available at: https://github.com/draganmarjanovic/stravasicht

TL;DR: Visualises Strava rides as a chart which grows each day.

Cheers!

**Comment by felixhageloh** [comment]
Interesting looking widget - thanks for sharing! I've added it

**Comment by draganmarjanovic** [comment]
Awesome - Cheers! 👍
