### ISSUE TITLE
Reddit karma widget

### ISSUE THREAD

**Issue by z3t0** [felixhageloh/uebersicht-widgets#291]
https://github.com/z3t0/reddit-karma.widget

**Comment by z3t0** [comment]
I can just create PR as well if you want

**Comment by felixhageloh** [comment]
No this is perfect, thanks for sharing!
There is one error (probably a typo) in your widget.json: it is missing a starting `{`

**Comment by z3t0** [comment]
Sorry about that, just pushed a commit

**Comment by felixhageloh** [comment]
np - I've added added it!
