### ISSUE TITLE
New Widget: pic-display.widget

### ISSUE THREAD

**Issue by Trapper777** [felixhageloh/uebersicht-widgets#293]
https://github.com/Trapper777/pic-display.widget

Ridiculously tiny widget that literally just displays a picture of your choice. Useful for doing those image overlap desktops you see on geektool [**a**](http://i.imgur.com/U9LVJUJ.png)ll [**t**](http://i.imgur.com/EM9nkv3.png)he [**t**](http://i.imgur.com/T1MQv.jpg)ime. It can also display animated GIFs, which could be useful.

**Comment by felixhageloh** [comment]
Hey thanks for sharing - looks like a great yet simple widget! There is one issue with your widget.json tho: it contains `“` instead of regular quotes `"` so the built script can't parse it.

**Comment by Trapper777** [comment]
Fixed.

**Comment by felixhageloh** [comment]
great, I've added it!
