### ISSUE TITLE
Simple iTunes Widget

### ISSUE THREAD

**Issue by pauloruberto** [felixhageloh/uebersicht-widgets#294]
https://github.com/pauloruberto/simple-itunes.widget

**Comment by felixhageloh** [comment]
sorry for the late reply - I was traveling last week, hence the delay. Thanks for sharing you widget! Can you add a screenshot and a widget manifest json file to your repo (details are in the readme)? I am using an automatic build script which will not work otherwise. Thanks!

**Comment by felixhageloh** [comment]
closing for now. Please let me know when/if you added manifest + screenshot file and I can add it
