### ISSUE TITLE
I made two wttr.in widgets

### ISSUE THREAD

**Issue by matthias-vogt** [felixhageloh/uebersicht-widgets#296]
Hi, would be nice if you could take a look at them :)
https://github.com/matthias-vogt/wttr-moon-uebersicht
https://github.com/matthias-vogt/wttr-uebersicht

**Comment by felixhageloh** [comment]
Great looking widgets! Thanks, I've added them

**Comment by matthias-vogt** [comment]
Nice! Thanks.

**Comment by matthias-vogt** [comment]
I just noticed that the screenshots are skewed on the plugin page and updated them
