### ISSUE TITLE
SpotifyCurrentTrack widget keeps Spotify open after 1.1(?) update

### ISSUE THREAD

**Issue by mrcheese123** [felixhageloh/uebersicht-widgets#297]
Whenever Ubersicht is open and the SpotifyCurrentTrack widget in active, it auto launches Spotify. If Spotify is then closed, it is automagically reopened. This is a new behavior after an Ubersicht update. I think it might be related to a change in the 'tell application' call, but I'm not sure.

**Comment by felixhageloh** [comment]
pinging the author of this widget :) @ThomasBrace

**Comment by ThomasBrace** [comment]
Thanks for the heads up, I'll take a look.

**Comment by felixhageloh** [comment]
(closing for now, feel free to follow up here)
