### ISSUE TITLE
GitHub Activity widget

### ISSUE THREAD

**Issue by shadowfacts** [felixhageloh/uebersicht-widgets#298]
Repo: https://github.com/shadowfacts/uebersicht-github-activity

**Comment by felixhageloh** [comment]
nice take on showing GitHub activity! Can you also add a `screenshot.jpg` file to your repo - that way I can add it to the gallery

**Comment by shadowfacts** [comment]
I've added screenshot.png to the repo

**Comment by felixhageloh** [comment]
awesome, added it to the gallery!
