### ISSUE TITLE
Simple ToDo Widget

### ISSUE THREAD

**Issue by illuminati945** [felixhageloh/uebersicht-widgets#299]
https://github.com/illuminati945/ToDo

**Comment by felixhageloh** [comment]
Hey thanks fro sharing! It looks like your widget.json contains `“` instead of regular quotes `"` (this can happen if you use TextEdit). You can fix it by disabling 'smart quotes' in TextEdit or by using a different text editor

**Comment by illuminati945** [comment]
It has been fixed, sorry for the trouble

**Comment by felixhageloh** [comment]
no problem - I've added it to the gallery!
