### ISSUE TITLE
Docker running containers widget

### ISSUE THREAD

**Issue by pauloamgomes** [felixhageloh/uebersicht-widgets#301]
This widget works as a wrapper for docker ps command using table format. More details in https://github.com/pauloamgomes/ubersicht-docker-containers

**Comment by felixhageloh** [comment]
Hey thanks for sharing! Could you also add a zip file of your widget to your repo (details are in the readme). It is required so that people can download it from the gallery.

**Comment by pauloamgomes** [comment]
Sure, I missed that part. Added.

**Comment by felixhageloh** [comment]
Awesome - I've added it to the gallery
