### ISSUE TITLE
Zendesk tickets by worker location using IP address. 

### ISSUE THREAD

**Issue by jagalbraith** [felixhageloh/uebersicht-widgets#303]
site: https://github.com/jagalbraith/Ubersicht_zendesk_jg.git

Features:

1. faded window on top left of screen. 
2. Only shows tickets with tags that are linked to your IP address. By default I have coded work and home. If you have a multi site position, when you connect to the wifi in the site you arrive at and your tickets update to the site you are on. 
3. Tickets are sorted by priority. Urgent, Hight, Normal, Low and color coded. Pink, White, Black, Grey.

Known issues:
1. The normal and low tickets have poor contrast in the window on dark backgrounds. I am new to coffee so if anyone has a suggestion on a good way to fix this, I am open to suggestions.

**Comment by felixhageloh** [comment]
thanks for sharing - added to the gallery!

**Comment by jagalbraith** [comment]
To update the app, do I just need to push to my Git repo or do you need a notification as well?

**Comment by felixhageloh** [comment]
you mean to update your widget?
