### ISSUE TITLE
Multiple Widget Authors

### ISSUE THREAD

**Issue by davidlday** [felixhageloh/uebersicht-widgets#304]
I've had a PR for one of my widgets and wanted to add the contributor as a co-author. The widget.json file seems to only accomodate a single author. Is that the case, and if so, since you're encouraging contribute / PR over creating new widgets, any chance you'll update the format to permit multiple authors?

**Comment by felixhageloh** [comment]
I have to double check, but I think the author field of the widget.json is just shown as is on the website, so you can add the name of your co-author there as well

**Comment by davidlday** [comment]
Apologies for leaving this open. What you've suggested works for me. Thank you!
