### ISSUE TITLE
taskpaper tasks on uebersicht

### ISSUE THREAD

**Issue by flow7** [felixhageloh/uebersicht-widgets#305]
Show [taskpaper](https://www.taskpaper.com) tasks with a specific tag on your desktop.
See [here](https://github.com/flow7/uebersicht-taskpaper) for the widget: https://github.com/flow7/uebersicht-taskpaper

**Comment by felixhageloh** [comment]
Hey thanks for sharing! Can you also add a widget.json file (details are in the readme) - it is required to be added to the gallery. Thanks!

**Comment by flow7** [comment]
done!
