### ISSUE TITLE
New Widget - Sonarr Download Queue Status

### ISSUE THREAD

**Issue by claylevering** [felixhageloh/uebersicht-widgets#306]
Hi all!  A Sonarr download queue status written with the new JSX format

https://github.com/claylevering/sonarr-widget

**Comment by felixhageloh** [comment]
Thanks for sharing, I've added it! I noticed there is an issue with your screenshot tho. I believe it is because it is stored using Git LFS, which the gallery currently doesn't support. If you add it as a regular  file it should work fine

**Comment by claylevering** [comment]
Fixed, @felixhageloh - thank you!
