### ISSUE TITLE
Hiya, I'm having trouble configuring your widget, can I trouble you to help me out, please?

### ISSUE THREAD

**Issue by JMarkyBB** [felixhageloh/uebersicht-widgets#309]
Can you help me from here felixhageloh please, I can't seem to edit the time zone? When I try to move clock face to right of my screen, it only moves one clock face?

![screenshot 2017-04-25 14 19 16](https://cloud.githubusercontent.com/assets/27829143/25387428/b25362ae-29c2-11e7-9901-98a2e341615a.png)

**Comment by felixhageloh** [comment]
hey there! For the time zone you can use either:

```
command: 'TZ=":GB" date +"%m/%d/%Y %I:%M:%S %p"'
```

or 

```
command: 'TZ=":Europe/London" date +"%m/%d/%Y %I:%M:%S %p"'
```

About moving the widget: It is hard to tell what might be going wrong from the screenshot. If this is somebodies widget you are modifying, maybe you can try pinging the author of the widget.

**Comment by felixhageloh** [comment]
I'm closing this issue btw, but feel free to follow up with questions

**Comment by JMarkyBB** [comment]
Cheers Felix, 

I figured it out, I was treating both faces as one widget, not two.

Thanks for the timezone help, its appreciated. 

Mark
