### ISSUE TITLE
Hiya, I'm having trouble configuring your widget, can I trouble you to help me out, please?

### ISSUE THREAD

**Issue by JMarkyBB** [felixhageloh/uebersicht-widgets#310]
Can you help me from here felixhageloh please?
![screenshot 2017-04-25 14 19 16](https://cloud.githubusercontent.com/assets/27829143/25387428/b25362ae-29c2-11e7-9901-98a2e341615a.png)

**Comment by felixhageloh** [comment]
hey sorry for the late reply - I remember answering to this one, but maybe it was on Disqus. Anyhow, can you provide more info on what you need help with?

**Comment by felixhageloh** [comment]
closed the Issue, because it is a question, but feel free to follow up
