### ISSUE TITLE
Yet Another Clock Widget: Valerian Time

### ISSUE THREAD

**Issue by arminrosu** [felixhageloh/uebersicht-widgets#311]
I did this a while back, maybe you like it enough to add it to the gallery.

https://github.com/arminrosu/valerian-time

**Comment by felixhageloh** [comment]
for a second I thought it was a valyrian time widget :D. 
Thanks, I've added it! It Currently shows quite low on the list, because the date order looks at the date of the last commit. If you want you can push a new commit to bump it up the list so it shows a 'new'.

**Comment by arminrosu** [comment]
Thanks!
