### ISSUE TITLE
Change API request from bitcoinaverage.com to cex.io

### ISSUE THREAD

**Issue by xxspartacusxx** [felixhageloh/uebersicht-widgets#313]
Hello,

Apologies if this is the wrong place to ask this question,

I use the [BTC](http://tracesof.net/uebersicht-widgets/#btc) widget on Uebersicht, but it's pulling the btc price from bitcoinaverage
`command: "curl -s https://api.bitcoinaverage.com/ticker/global/USD/last"`

I would like to replace the price with the CEX.io one, since they always differ.

Could you please let me know what I need to change to make that happen?

Thank you for your help and time!

**Comment by felixhageloh** [comment]
Hi! It is an old widget without its own repo, so this is the best pace to ask questions I guess. Let's ping the author @dansku - maybe he can help you further!

**Comment by felixhageloh** [comment]
closing this as an issue (because it is not actionable), but feel free to follow up here!

**Comment by dansku** [comment]
Hi, you need to find another place to get the data from.
Something like:
http://api.coindesk.com/v1/bpi/currentprice.json 

You will need to change the code to make it work with this specific one.

**Comment by xxspartacusxx** [comment]
Thank you @felixhageloh for your continuous help :)

Hi @dansku - I did try to pull the date from:
(https://cex.io/rest-api)

simply by changing the source you used to the one from cex.io site:
`GET https://cex.io/api/ticker/BTC/USD`
However I sure haven't done it correctly.

Could you please point me in the right direction, I highly appreciate your help
