### ISSUE TITLE
Ethereum price widget

### ISSUE THREAD

**Issue by AdrienKuhn** [felixhageloh/uebersicht-widgets#315]
Ethereum price in USD with change percentage.

https://github.com/AdrienKuhn/uebersicht-ethereum-usd-price

**Comment by felixhageloh** [comment]
Hey thanks for sharing! There is a trailing comma in your widget.json file, so the build script breaks (JSON parser are very strict about trailing commas :/)

**Comment by AdrienKuhn** [comment]
Hi @felixhageloh , I removed the trailing comma. Thanks!

**Comment by felixhageloh** [comment]
awesome, I've added it!

**Comment by AdrienKuhn** [comment]
Hi @felixhageloh, I've updated the widget due to breaking changes on ethereumprice.org.

https://github.com/AdrienKuhn/uebersicht-ethereum-usd-price

Thanks!

**Comment by felixhageloh** [comment]
👍 Changes to widgets should automatically make it to the gallery, as long as you update the zip file in your repo. (sometimes you need to wait for caches to expire to see the changes)
