### ISSUE TITLE
New Widget: conk-for-mac

### ISSUE THREAD

**Issue by dumbo25** [felixhageloh/uebersicht-widgets#317]
https://github.com/dumbo25/conky-for-mac

**Comment by felixhageloh** [comment]
hey thanks for sharing, can you also add a widget manifest and a zip file (details are in the readme)? I is required by the build script for the widget gallery

**Comment by dumbo25** [comment]
I love Übersicht! I made the changes. Hopefully, I did everything correctly.

**Comment by felixhageloh** [comment]
almost there :) If you rename 'conky screenshot.png' to just 'screenshot.png' the script can pick it up. Glad you like Übersicht; conky was actually my main inspiration when I wrote it, so I am happy to see a conly-like widget!

**Comment by dumbo25** [comment]
renamed to screenshot.png

**Comment by felixhageloh** [comment]
great! I've added it
