### ISSUE TITLE
Request Caps lock for interaction Shortcut

### ISSUE THREAD

**Issue by aatvanrees** [felixhageloh/uebersicht-widgets#318]
First of all thank you for making Übersicht, it's simply amazing!
I'm using it to show realtime orders for a food delivery store on the desktop.
Question though: Would it be posible to use the caps lock button as interaction shortcut.
Off = default behaviour, On = interaction behaviour. I'm now using the shift button, this works fine but it would be more user friendly especially for the scrollbar behaviour.

**Comment by felixhageloh** [comment]
If I understand correctly, you essentially want a way to toggle Übersicht into 'interaction mode' for longer periods of time (and not having to press a key for every interaction)?

Glad you like the app btw :)
