### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by Diskutant** [felixhageloh/uebersicht-widgets#319]
bitcoinaverage changed their api. Now the widget only shows "301 Moved Permanently - nginx/1.10.1".

Just realised this is a repo for all widgets. The issue is for the btc-eur widget (and others that use bitcoinaverage).

**Comment by theIuser** [comment]
To temporary fix it change in btc.coffee

```
command: "curl -s https://apiv2.bitcoinaverage.com/ticker/global/USD/last"

refreshFrequency: 900000 #ms
```

You have to lower the request to 15 min because bitcoinaverage only allows 100 request per day.

**Comment by felixhageloh** [comment]
pinging the author of the widget :) @cesckat

**Comment by Diskutant** [comment]
They seem to have changed the api again.

New URL: 

`command: "curl -s https://apiv2.bitcoinaverage.com/indices/global/ticker/BTCEUR"`

new render method:

```
render: (o) -> """
      <div class='col1'>#{$.parseJSON(o).last}€</div>
"""
```
