### ISSUE TITLE
Cryptocurrency Widget

### ISSUE THREAD

**Issue by avocadomaster** [felixhageloh/uebersicht-widgets#322]
https://github.com/avocadomaster/cryptowidget

**Comment by felixhageloh** [comment]
Hey, thanks for sharing! I'm traveling at the moment and am not able to update the gallery at the moment. I'm hoping to add it the coming week - sorry for the delay!

**Comment by felixhageloh** [comment]
Alright, I've finally added it. Sorry again for the delay
