### ISSUE TITLE
Central image display

### ISSUE THREAD

**Issue by aykot** [felixhageloh/uebersicht-widgets#323]
https://github.com/aykot/uebersicht-central-logo-widget
Been fiddling with this for my setup, so I thought in sharing it.
Regards

**Comment by felixhageloh** [comment]
Hey, thanks for sharing! I'm traveling at the moment and am not able to update the gallery at the moment. I'm hoping to add it the coming week - sorry for the delay!

**Comment by aykot** [comment]
No problem! Enjoy your travel ;)

**Comment by felixhageloh** [comment]
Thanks for you patience! Could you also add a widget.json file (detail in the readme). It is needed for the build script to add it to the gallery

**Comment by aykot** [comment]
Done

**Comment by felixhageloh** [comment]
great! I've added it
