### ISSUE TITLE
Authentic Weather - JSON Parse Error: Unexpected identifier "Cannot"

### ISSUE THREAD

**Issue by devilzSoul** [felixhageloh/uebersicht-widgets#324]
Installed Authentic weather (http://tracesof.net/uebersicht-widgets/#authentic-weather) on UberSicht version 1.2(48). But I am getting the error "JSON Parse Error: Unexpected identifier "Cannot"" . I haven't modified authentic.coffee at all. 

I am not sure what steps I need to take to correct it. I removed and installed latest version of widget and ubersicht again. Tried looking through Authentic.coffee in editor (Used Atom by Github) to see if there is any issue. but cant seem to find any. 

Can anyone please help as to what are the possible reasons that I should look for?

**Comment by felixhageloh** [comment]
I think you might have to set up your forecast API key first (mentioned in the readme of the widget). In any case, if you have more questions you can create an issue on the widget's repo directly https://github.com/reduxd/authentic-ubersicht. The widget's author will be able to help you out better than I can
