### ISSUE TITLE
Widget Submission

### ISSUE THREAD

**Issue by aprowe** [felixhageloh/uebersicht-widgets#326]
Hello, I have created a widget and would like to submit it to the gallery!

https://github.com/aprowe/mini-system-charts.widget

It is a small collection of system info charts that are tiny and can be put in a status bar on the top of your screen.
<img width="422" alt="screen shot 2017-07-22 at 3 50 32 am" src="https://user-images.githubusercontent.com/7191456/28489778-eed7bf64-6e90-11e7-8749-a551b4ff4a57.png">

Thanks for your effort, I really enjoy creating Übersicht widgets!

**Comment by felixhageloh** [comment]
nice looking widget; reminds me of Conky! I've added it to the gallery.

Small heads up: the screenshot currently looks squashed in the gallery. To fix it you can make sure that your screenshot is 258x160px or 516x320px for retina (recommend). You can still use your current screenshot inside your readme btw - just use a different name than `screenshot.png`

**Comment by aprowe** [comment]
Okay I added a different screenshot. Thanks!
