### ISSUE TITLE
Widget: Swiss police ticker

### ISSUE THREAD

**Issue by gbuendia** [felixhageloh/uebersicht-widgets#329]
A scrolling ticker that pulls headlines from Polizeiticker.ch (in German).

Switzerland-centered.

https://github.com/gbuendia/uebersicht_polizeiticker_widget

**Comment by felixhageloh** [comment]
and once again, thanks for sharing! I've also added it

**Comment by gbuendia** [comment]
Hi, I'm sorry to inform that the widget cannot pull headlines because the page is no longer offering an RSS channel (at least publicly). It is something out of my control, so this looks like a definitive discontinuation for the widget :(

**Comment by felixhageloh** [comment]
Sorry to hear! I removed it from the gallery for now
