### ISSUE TITLE
Widget: trello card information

### ISSUE THREAD

**Issue by guxsousa** [felixhageloh/uebersicht-widgets#331]
A fetcher widget that displays information from a chosen trello card

https://github.com/guxsousa/trellocard

**Comment by felixhageloh** [comment]
Hey thanks for sharing! Your widget still needs a manifest json file (details in readme) so I can add it to the gallery

**Comment by guxsousa** [comment]
Done, Cheers!

**Comment by felixhageloh** [comment]
👍 I've added it to the gallery
