### ISSUE TITLE
There's always a \ at the end of the task

### ISSUE THREAD

**Issue by DinoAlbatross** [felixhageloh/uebersicht-widgets#332]
For example:
1. This is some example text.\
2. This is some example text but without a fullstop\

Any help?

**Comment by felixhageloh** [comment]
Sorry for the late response! Which widget are you referring to?

**Comment by DinoAlbatross** [comment]
Oops, I forgot to mention it! It's the to do list widget that displays a to do list based off of a .rtf file.
Here is a screenshot. Ignore the mail count, that's working fine.
<img width="443" alt="screen shot 2017-11-05 at 5 57 44 pm" src="https://user-images.githubusercontent.com/21858194/32412664-0159f43e-c253-11e7-90b5-0ac4d47ac42c.png">

**Comment by felixhageloh** [comment]
I see! It is not one of my widgets - have you tried pinging the author of the widget?
