### ISSUE TITLE
Widget: wanikani information card

### ISSUE THREAD

**Issue by jakeoid** [felixhageloh/uebersicht-widgets#333]
A fetcher that displays reviews and lessons counts from Wanikani

https://github.com/jakeoid/ubersicht-wanikani

**Comment by felixhageloh** [comment]
hey thanks for sharing! Can you also add a screenshot to your repo (details are in the readme) - it is needed to be added to the gallery .

**Comment by jakeoid** [comment]
As in `https://github.com/jakeoid/ubersicht-wanikani/blob/master/preview.png` ?

**Comment by felixhageloh** [comment]
Almost! It should be called `screenshot.png` https://github.com/felixhageloh/uebersicht-widgets#readme

I am using an automatic build script, so it looks for specific names.

**Comment by jakeoid** [comment]
Okely dokely! Gimmie 2 secs.

**Comment by felixhageloh** [comment]
sorry did not see the edit! It is on the gallery now
