### ISSUE TITLE
Add stvhwrd/Strava

### ISSUE THREAD

**Issue by stvhwrd** [felixhageloh/uebersicht-widgets#334]
Add https://github.com/stvhwrd/Strava.widget to the list!

**Comment by felixhageloh** [comment]
Hey thanks for sharing! You mention it is a fork of an existing widget. Are there any chances other than styling (some extra features)?

**Comment by stvhwrd** [comment]
Nope! Pretty much just styling... if you'd rather add the original, that might actually make more sense. 👍

**Comment by felixhageloh** [comment]
the original is already in the gallery :) I noticed because the name was already taken. Thanks for understanding

**Comment by stvhwrd** [comment]
I didn't see that it was already there! Sorry about that.  Thanks for all that you do!
