### ISSUE TITLE
Calendar Formatting

### ISSUE THREAD

**Issue by deangwilcox** [felixhageloh/uebersicht-widgets#336]
Since upgrading to Mac OS High Sierra, the current day's highlighting is not rendering correctly. Screenshot enclosed (showing today's date 10/6/17. Any insight is appreciated .
![screen shot 2017-10-06 at 8 07 21 am](https://user-images.githubusercontent.com/32575945/31285976-9e5799d4-aa71-11e7-9a3e-baad641fbb42.png)

**Comment by felixhageloh** [comment]
I believe the solution is in this thread https://github.com/felixhageloh/uebersicht-widgets/issues/335

**Comment by deangwilcox** [comment]
Perfect! Thx.
