### ISSUE TITLE
On the present day, I've been seeing underscores on my calendar instead of the highlighted oval

### ISSUE THREAD

**Issue by JMarkyBB** [felixhageloh/uebersicht-widgets#337]
I've been having issues lately with your calendar, On the present day, I've been seeing underscores and no numbers/dates on my calendar instead of the highlighted oval I used to see, can you offer a solution Felix?

**Comment by felixhageloh** [comment]
Relevant discussion (and fix) is here https://github.com/felixhageloh/uebersicht-widgets/issues/335

It is not my widget, but I will see if I can update it nonetheless

**Comment by felixhageloh** [comment]
closing this as a duplicate
