### ISSUE TITLE
Text formatting issue

### ISSUE THREAD

**Issue by monkeemunk** [felixhageloh/uebersicht-widgets#338]
![screen shot 2017-10-09 at 4 12 20 pm](https://user-images.githubusercontent.com/32652600/31356611-a62a9362-ad0c-11e7-99ff-708a4d99f306.png)

Getting the issue in the attached screenshot. Any ideas? I tried to tinker with the code to find out what the source of the issue is but no luck

**Comment by Takuro123** [comment]
I think something changed in High Sierra where-in "today" ends up with some extra underscores before it. I found that changing the top line of index.coffee fixes this by stripping out any characters from the "cal" command that aren't alphanumerics or space characters, which effectively strips out the underscores and allows the widget to behave properly.

`sundayFirstCalendar = 'cal | sed "s/[^a-zA-Z 0-9]//g" && date "+%-m %-d %y"'`

**Comment by felixhageloh** [comment]
Fix can be found here as well https://github.com/felixhageloh/uebersicht-widgets/issues/335

**Comment by felixhageloh** [comment]
The widget on the gallery should be fixed now as well, so you can download the new version
