### ISSUE TITLE
Revamped new version of Public IP widget

### ISSUE THREAD

**Issue by i07** [felixhageloh/uebersicht-widgets#339]
Just revamped and 'updated' the current public_ip widget.

https://github.com/i07/uebersicht-widget-public_ip/tree/master/release

perhaps contact the original author of public_ip ( I couldn't, his github account doesn't exist anymore). Or add this as a new widget public_ip2 ;)

**Comment by felixhageloh** [comment]
Hey really sorry for the super late response. I just noticed that email notifications from this repo were ending up in my spam folder. 

I'll gladly add your widget to the repo (I'll leave the original in place for now). Only thing missing is a screenshot in your repo, so the automatic build script can pick it up

**Comment by i07** [comment]
Hey, no worries.

Thanks, I've added the screenshot to the src/public_ip2.widget folder.

I assumed being in the release folder was what you were after ;) Let me know if it's ok like that, otherwise i'll fix it up anyway you need to have it..

Cheers,
Marc

**Comment by felixhageloh** [comment]
Thanks! It needs to be in the root of the repo (details are in the [readme](https://github.com/felixhageloh/uebersicht-widgets#readme))

**Comment by i07** [comment]
Sorry for the delay, I have moved the release version to the root of the repo

**Comment by felixhageloh** [comment]
Thanks! added to the gallery now!
