### ISSUE TITLE
a bar that display useful info in the bottom of your desktop

### ISSUE THREAD

**Issue by zsugiart** [felixhageloh/uebersicht-widgets#341]
Wrote this in 2015 and forgot to upload. thought good to share ! not sure if it'll work on people's env or not, give it a shot.

https://github.com/zsugiart/widget.ubersicht/tree/master/ZENOSX.widget

make sure folder name is ZENOSX.widget
and place it inside the widget folder. 
Also, make sure python is installed.

**Comment by felixhageloh** [comment]
Hey thanks for sharing and sorry for the late reply -I haven't been getting notifications from this repo!

The way the gallery currently works, it expects one widget per repo and the widget should be at the root of the repo. So if you can move the ZENOSX.widget to the root of your repo (or make a new one) I can add it!

**Comment by felixhageloh** [comment]
closing for now
