### ISSUE TITLE
cuteical widget

### ISSUE THREAD

**Issue by ctakemoto** [felixhageloh/uebersicht-widgets#345]
https://github.com/ctakemoto/cuteical.widget

**Comment by felixhageloh** [comment]
Hey thanks for sharing and sorry for the late response. Can you rename `Screen_Shot.png` to `screenshot.png`? That way the automatic build script can pick it up.

**Comment by ctakemoto** [comment]
Should be updated now. Thank you!

**Comment by felixhageloh** [comment]
great, I've added it to the gallery!
