### ISSUE TITLE
Simple Stocks: Yahoo Finance API Removed

### ISSUE THREAD

**Issue by Raab70** [felixhageloh/uebersicht-widgets#348]
The Simple Stocks widget was based on the yahoo finance API which has been removed. The cURL command now returns a 403 with a message that this API has been removed: 

```
$ curl -s 'http://download.finance.yahoo.com/d/quotes.csv?s=AAPL&f=sl1c1p2' | sed 's/\"//g'
<html><head><title>Yahoo! - 403 Forbidden  -- error 403</title></head><body>It has come to our attention that this service is being used in violation of the Yahoo Terms of Service.  As such, the service is being discontinued.  For all future markets and equities data research, please refer to finance.yahoo.com.</body></html>
```

**Comment by edasque** [comment]
I have rebuilt my own Simple Stock widget to use the RobinHood API. As a result it's US stock exchanges only but it works very reliably and fast. I am happy to clean up the code and submit.

It's a change to https://github.com/edasque/Stock-quotes-Widget/tree/968769c4e557337ee25c92bfa1bace8062e410cb that's not yet committed.

**Comment by Raab70** [comment]
If you want to send me a finished commit I'd be happy to lend a hand testing.

**Comment by edasque** [comment]
I would need help figuring out installation instructions. There might be some hard coded paths that need tinkering with. Stock config is in config.json

**Comment by Raab70** [comment]
Out of the box I got an error in the debug console with the `cd`, Turns out my directory name had `-master` at the end. Be sure it's clear that the directory naming needs to be the same to work in install instructions. 

After that it works exactly as above. I would also add some documentation for how to change it's position (same as every other widget) and how to add/remove stocks from the ticker.

**Comment by Raab70** [comment]
I have encountered one error, is there any way to access index ticker symbols? Previously I had used `^DJI` as a ticket symbol and this now produces:
```
$ ./get_stocks_info
Float conversion error: strconv.ParseFloat: parsing "": invalid syntax, strconv.ParseFloat: parsing "": invalid syntax
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.getQuotesFromRHYearWorthOfDays(0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/ed/Dropbox/Application Support/Ubersicht_Widgets/Stock-quotes-Widget/stock.widget/src/get_stocks_info.go:77 +0x46b
main.main()
	/Users/ed/Dropbox/Application Support/Ubersicht_Widgets/Stock-quotes-Widget/stock.widget/src/get_stocks_info.go:227 +0x4a6
```

**Comment by Raab70** [comment]
I've also updated the command to the following:
`command: 'cd stock.widget/src/ && ./get_stocks_info'` 

This has two advantages:

1. It follows the naming protocol and install instructions previously of copying just the `stock.widget` directory into your widgets directory
2. `get_stocks_info` will only be executed if the cd command is successful.

**Comment by edasque** [comment]
@Raab70 unfortunately the RH API doesn't support indices unfortunately. I've not found an alternative API to use, especially one that provides rt stock info and great historical info (for the sparklines), so I went ahead and gave up on indices.

**Comment by bdpiper** [comment]
I missed the simple stock widget, so grabbed this when I saw the discussion. Installation went smoothly, once I plugged in the "cd" update above. Edited the stocks and it is off an running! I really like the format, the sparkles are great! Even if they do graphically illustrate my lack of skill at picking stocks... Thanks for doing this...

**Comment by edasque** [comment]
Glad to hear it's working well for you @bdpiper.

I need to update the doc to indicate this is now US exchanges only and does't support indices - as well as change the path.

**Comment by maikeru1202** [comment]
Thank you edasque.  Could we try to add currencies as well?  Maybe use google finance instead of robinhood?

**Comment by edasque** [comment]
Google Finance API has been deprecated. As as Yahoo Finance API apparently. RH API was the only one that gave me up to date and historical stock data for 'free'. If you can suggest something that's free for everyone and that I can use, I'd be happy to take a look.

**Comment by edasque** [comment]
Ok, I finished the doc for the https://github.com/edasque/Stock-quotes-Widget updated.
