### ISSUE TITLE
GitFinder widget updated

### ISSUE THREAD

**Issue by atika** [felixhageloh/uebersicht-widgets#349]
I modified the widget to avoid duplicates project paths.
And now the widget displays also Git statistics for the current/active Xcode Project.

https://github.com/atika/Ubersicht-GitFinder

**Comment by felixhageloh** [comment]
Hey, sorry for the late reply. The gallery directly points to your repo, so any updates you make through there. Let me know if that is not the case (sometimes it might take a while because of caching)

**Comment by atika** [comment]
No Problem. It just I thought that I had to send you a notification about the update, because on GitHub, the submodule point to a old branch on the tree.
