### ISSUE TITLE
Wunderlist Tasks Widget fixed

### ISSUE THREAD

**Issue by Makiah** [felixhageloh/uebersicht-widgets#351]
The prior one uses an obsolete API (Wunderlist has transitioned away from basic authentication), this one (rewritten from scratch, so I didn't fork the original) opens Safari and uses OAuth2 to authenticate the user, then displays available tasks.  https://github.com/Makiah/WunderlistTasksWidget

**Comment by felixhageloh** [comment]
Hi, thanks for sharing your fix for this widget! Can you add a screenshot file called screenshot.png to the root of the repo? That way the build script for the gallery can pick it up

**Comment by Makiah** [comment]
Absolutely!  Thanks for the reminder.

**Comment by felixhageloh** [comment]
great, I've added it to the gallery!
