### ISSUE TITLE
New widget: Unobtrusive Dashboard

### ISSUE THREAD

**Issue by williamadamafromcaprica** [felixhageloh/uebersicht-widgets#352]
Unobtrusive dashboard with dual clock/weather, calendar, bluetooth battery indicator, top CPU & memory usage and trash size.

URL: https://github.com/williamadamafromcaprica/unobtrusive-dashboard-for-ubersicht

**Comment by felixhageloh** [comment]
Hi, thanks for sharing! If I understand correctly, this is a collection of existing widgets with some extra styling?

**Comment by williamadamafromcaprica** [comment]
Hey Felix, sorry for the late reply. This is a collection but not with just
extra styling, many features have been modified and improved. Thanks!
