### ISSUE TITLE
Updated Widget: Reminders

### ISSUE THREAD

**Issue by davidlday** [felixhageloh/uebersicht-widgets#376]
I've updated the Reminders widget: https://github.com/davidlday/RemindersWidget/releases/tag/v1.1.0

**Comment by davidlday** [comment]
Also - I'd like to contribute some simple documentations on how I implemented custom themes. I've had a few folks ask me about it over the past year or so. Do you have a preference on where documentation is contributed? Wiki page here, or main Uebersicht repo, or somewhere else?

**Comment by felixhageloh** [comment]
Hi! The widget should automatically update on the gallery (it points straight to your repo). About the documentation: a PR on the Uebersicht repo is the way to go - thanks for wanting to contribute!
