### ISSUE TITLE
Update zip file link

### ISSUE THREAD

**Issue by cliveza** [felixhageloh/uebersicht-widgets#386]
Hi Felix,

I renamed my repo from `https://github.com/zagno/kubernetes-widget`  to`https://github.com/zagno/kubernetes.widget`. I replaced the dash with a period so the naming is more uniform.

Could you update the link to the zip file on the widgets gallery please, Im not sure how long GitHub keep the redirect for, thanks

**Comment by felixhageloh** [comment]
hey, sorry for the super late reply. I've updated the gallery to reflect the change! The downside is that your download count will be reset to 0
