### ISSUE TITLE
New widget: Hello widget

### ISSUE THREAD

**Issue by Dudecorn** [felixhageloh/uebersicht-widgets#392]
# A simple widget for Übersicht that displays greetings depending on the time of day.
## [https://github.com/Dudecorn/Hello-Widget.git](url)
![Hello widget screenshot](https://github.com/Dudecorn/Hello-Widget/blob/master/screenshot.png?raw=true "Screenshot of Hello widget")

**Comment by felixhageloh** [comment]
Hi, thanks for sharing. There is actually a widget submit form on the widget gallery now that will also guide you through creating a widget repo. Please use the form to submit this widget again
