### ISSUE TITLE
Calendar widget - Previous/Next months

### ISSUE THREAD

**Issue by CTF01** [felixhageloh/uebersicht-widgets#394]
For the simple calendar widget, http://tracesof.net/uebersicht-widgets/#calendar
Would it be possible to have a variable to show the previous and next month as well?
Or maybe a variable that allows to pick # of prior months and following months to show.
Thank you.

**Comment by Freakwill** [comment]
create it by yourself. You can use calendar module of python directly.
(pycalendar)[https://github.com/Freakwill/pycalendar/upload]

**Comment by CTF01** [comment]
Thank you for the update and link, I will check this out.
My last programming experience was 15 years ago in VB, and I do not know Python which is why I was asking if it is easy to do or not. :-)
My apologies for not asking the author, I thought I was. 
Not much experience with Github either I am afraid..
Thank you.
