### ISSUE TITLE
I found a pseudo-bug

### ISSUE THREAD

**Issue by Freakwill** [felixhageloh/uebersicht-widgets#397]
The images only can be found in the folder `widgets`, but can not be found in the subfolders (folders of widgets) regardless whether the path is relative or absolute. It is unreasonable. And It is unable to use absolute path, e.g. `/Users/william/Library/Application Support/Übersicht/widgets/übersicht-logo.png` in `getting-started.coffee`.

**Comment by felixhageloh** [comment]
do you have an example where this breaks? I was unable to reproduce

**Comment by Freakwill** [comment]
If I replace 'übersicht-logo.png' with '/Users/william/Library/Application Support/Übersicht/widgets/übersicht-logo.png' in `getting-started.coffee`, then the logo just disappear. But  './übersicht-logo.png' is Ok.

I made a widget, `quote.widget`, if I put the image under the folder `quote.widget` and use absolute path or `image` relatively  in stylus code, then it will no be found. Hence I have to put it under the `widgets` folder, and use path `../image`.

Following is unfeasible.
quote.widget
|
| --- image
| --- index.coffee  # url{image}

**Comment by Freakwill** [comment]
I know what is the problem. It should be a relative path `url('quote.widget/flower.png')`. When running command in .coffee file of `quote.widget`, ubersicht tries to find images under `widgets` instead of `quote.widget`. I do not think it is convenient. It makes the results of command and running script.py directly different.

I hope that you can tweak it. Indeed It is not a bug.
