### ISSUE TITLE
New widget: True binary clock

### ISSUE THREAD

**Issue by dr-mod** [felixhageloh/uebersicht-widgets#399]
Please add this widget to the gallery: https://github.com/dr-mod/true-binary-mode-clock

**Comment by felixhageloh** [comment]
Hi, thanks for sharing! Is this a mod/fix of the exiting binary clock widget?

**Comment by dr-mod** [comment]
Hi Felix, this widget is not related to the existing binary clock widget. 
The one that you have in the library represents each decimal digit in the binary format. The widget I’ve sent, while also using binary numbers, treats hours/minutes/seconds as values that are translated to binary directly. Hence the name “True binary mode clock”. This format is inspired by numerous binary clocks for Gnome/Linux.

Moreover, battery life is quite important to me, so this widget has been written from scratch in order to drain less energy from user’s battery. 

On my MacBook the energy impact is almost three times less when compared with the existing plugin (0.7 points vs 2.0 points) according to Activity Monitor.
I’d like to share the widget so the other people who like a bit more challenging true binary mode clocks could benefit of a longer battery life.

**Comment by felixhageloh** [comment]
awesome, thanks again! I've added it
