### ISSUE TITLE
New Widget: Timezones

### ISSUE THREAD

**Issue by kusold** [felixhageloh/uebersicht-widgets#400]
https://github.com/kusold/timezones.widget

This looks to be the first JSX widget. Any feedback is appreciated.

**Comment by felixhageloh** [comment]
Nice, cool to see a JSX widget -  thanks for sharing! 

If you use the form on the website it will ensure that it is in the right format to be added to the gallery (it looks like a manifest file is missing currently). 

About the widget itself: 
Be aware that the api for JSX widgets might still change in the next release. Specifically, I think the order of arguments for `updateProps` will change from `(action, state)` to `(state, action)`.
