### ISSUE TITLE
New widget: Modifiable clock

### ISSUE THREAD

**Issue by daliife** [felixhageloh/uebersicht-widgets#407]
Please add this widget to the gallery if you find it interesting. [https://github.com/daliife/modifiable-clock](https://github.com/daliife/modifiable-clock)
It's just a more modifiable and customizable version of the _simple Clock_ version.

Great app Übersicht, by the way! Cheers!

**Comment by felixhageloh** [comment]
Thanks, glad you enjoy it! I've added your widget
