### ISSUE TITLE
New widget: Transmission

### ISSUE THREAD

**Issue by Sesquipedalian** [felixhageloh/uebersicht-widgets#411]
Please add this widget to the gallery: https://github.com/Sesquipedalian/transmission-uebersicht

**Comment by Sesquipedalian** [comment]
Is there something I need to do before this widget can be added?

**Comment by Sesquipedalian** [comment]
No need to apologize. We're all busy people. 🙂

> could you maybe change the screenshot to something without 'pwned-passwords' ?

😆 Done. (FYI, that was an academic dataset for computer science research, but I understand why you'd prefer something with a different name.)

**Comment by felixhageloh** [comment]
Hah ok, I wasn't sure :); thanks for understanding. I've added it!
