### ISSUE TITLE
Python3: Command not found

### ISSUE THREAD

**Issue by ChausseBenjamin** [felixhageloh/uebersicht-widgets#412]
I recently updated my mac and I keep getting this error.

The console debug is the following:

    [Error] Inbox-for-Todoist-inbox_for_todoist-widget-index-coffee: – Error: run.sh: line 2: python3: command not found
     — client.js:1:749223
    Error: run.sh: line 2: python3: command not found
     — client.js:1:749223
    	redraw (client.js:1:734729)
    	(anonymous function) (client.js:1:733256)
    	callback (client.js:1:719471)
    	(anonymous function) (client.js:1:715770)
    	emit (client.js:1:498453)
    	onreadystatechange (client.js:1:720926)

I have tried: 
-    Reinstalling python3 from homebrew
-    Reinstalling python3 from python.org
-    Linking python3 to homebrew after having it installed
-    I have no idea how to setup the BASH env so I would't know how to use it 

As the developper of [Inbox for Todoist](http://tracesof.net/uebersicht-widgets/#Inbox-for-Todoist) I'd like to fix this issue as fast as possible to prevent other of having the same issue and to continue developing my widget.

Thanks!

**Comment by felixhageloh** [comment]
as a quick fix you can use the full path to the python3 executable in your command. `which pthon3` will give you the full path

**Comment by ChausseBenjamin** [comment]
I tried replacing python3 with usr/local/bin/python3 which was the directory for which python3.
It only resulted in the following:

    error:  usr/local/bin/python3: no such file or directory

The weird thing is that this file path is precisely what is outputted by which python3

**Comment by felixhageloh** [comment]
The path is missing a leading slash I think:

‘/usr/local/bin/python3’
