### ISSUE TITLE
New widget: Margins

### ISSUE THREAD

**Issue by Sesquipedalian** [felixhageloh/uebersicht-widgets#414]
Please add this widget to the gallery: https://github.com/Sesquipedalian/margins-uebersicht

**Comment by felixhageloh** [comment]
Interesting! I've added it

**Comment by Sesquipedalian** [comment]
Thanks. I'm glad to see it go in. Reverse engineering the formulae for the desktop icon grid spacing was particularly time consuming, so I'm happy to see that others will be able to benefit from it.

**Comment by Sesquipedalian** [comment]
By the way, if at some point you decide to integrate this functionality directly into Übersicht, by all means feel free to use whatever you want from this code. (I released it under the CC0 license for a reason, after all.)
