### ISSUE TITLE
Updated widget: YouTube

### ISSUE THREAD

**Issue by atika** [felixhageloh/uebersicht-widgets#415]
I have updated the YouTube widget. I written a utility in Golang to access the YouTube API and to simplify the installation. It get the informations about the channel and returns a JSON for the widget.

https://github.com/atika/Ubersicht-Youtube

**Comment by felixhageloh** [comment]
nice! The widget should update automatically (it might take a while because of caching), so no action required from me

**Comment by atika** [comment]
OK, sorry. I thought that you have to update the submodule manually. It's a pity that it stays on the bottom of the page as it was just been updated and users will not take care of the new content.
