### ISSUE TITLE
Help with Morning widget

### ISSUE THREAD

**Issue by Pearcey1409** [felixhageloh/uebersicht-widgets#417]
Hello can you please help me? I downloaded this widget and I love it. I have two displays it works perfectly on my laptop screen as is dead centre. But on my big TV external display the widget is not in the middle and slightly to the side which is driving me crazy, how can I move it to the correct position? Please help! thanks
![screenshot 2019-01-04 at 13 44 57](https://user-images.githubusercontent.com/46364312/50673027-1eeb0b00-1027-11e9-8210-8ebedc2cee41.png)

**Comment by alex-taxiera** [comment]
Have you downloaded this from the widget gallery? It looks like they have updated the code on their repo, but not in the zip file. I think the [updated version](https://github.com/imRohan/ubersicht-morning.widget/blob/master/morning.widget/morning.coffee) might work.
