### ISSUE TITLE
New widget: ubersicht-calendar

### ISSUE THREAD

**Issue by kknopper** [felixhageloh/uebersicht-widgets#424]
Please add this widget to the gallery: https://github.com/kknopper/ubersicht-calendar

This widget is a fix for the current simple-calendar widget that fixes a bug with highlighting the current day of the month.

This widget also allows you to set any day of the week as the start day for your calendar.

**Comment by felixhageloh** [comment]
Thanks for sharing and sorry for the delay! I've added it
