### ISSUE TITLE
New widget: check-proxyUrls

### ISSUE THREAD

**Issue by jerryma0912** [felixhageloh/uebersicht-widgets#438]
Please add this widget to the gallery: https://github.com/jerryma0912/check-proxyUrls

**Comment by felixhageloh** [comment]
Hi thanks for sharing and sorry for the late reply. It looks like your widget is missing a zip file containing the bundled widget code. You can check the README for details

**Comment by jerryma0912** [comment]
hi, I have modified the file's structure. Please check.

**Comment by felixhageloh** [comment]
all working now! I've added the widget
