### ISSUE TITLE
New Widget: Canadian Weather Radar

### ISSUE THREAD

**Issue by openfirmware** [felixhageloh/uebersicht-widgets#439]
I created a widget for showing the weather radar on a map.

https://github.com/openfirmware/canada_radar.widget

 I included shortcuts for a few map tile providers, and some additional screenshots in the repo. I only included support for Canada at the moment, as I am not sure about what radar sources to use for other parts of the world.

**Comment by felixhageloh** [comment]
Thanks, I've added it to the gallery! No worries that it is for Canada only. You description clearly states so and it can serve as a starting point for others!
