### ISSUE TITLE
New widget: gaudi

### ISSUE THREAD

**Issue by ahmadassaf** [felixhageloh/uebersicht-widgets#444]
Please add this widget to the gallery: https://github.com/ahmadassaf/gaudi-widgets

**Comment by felixhageloh** [comment]
Nice looking widgets! As is I can't add them to the gallery tho: If you go to http://tracesof.net/uebersicht-widgets/ and click 'submit your own' in the top right, you will get a tool that will guide you through the steps of preparing your repo for submission

**Comment by felixhageloh** [comment]
closing for now - feel free to re-open when ready for submission
