### ISSUE TITLE
New Widget: simple-neo-clock

### ISSUE THREAD

**Issue by c0dine** [felixhageloh/uebersicht-widgets#457]
# My widget 
My widget is a neomorphic clock inspired by simple-clock
![Widget-IMG](https://user-images.githubusercontent.com/56287516/77808071-4c1a4380-7047-11ea-9d9d-3b1c4cdfa7b3.png)

There are a few things that I want to add in the future
- [ ] Color Options!
- [ ] Blur Options
- [ ] Animations

The widget URL is: [github.com](https://github.com/c0dine/simple-neo-clock)

**Comment by felixhageloh** [comment]
thanks for sharing! Please use the form on the widget gallery to ensure you repo is ready for submitting http://tracesof.net/uebersicht-widgets/#submit

**Comment by c0dine** [comment]
Ok!

**Comment by c0dine** [comment]
Its been verified!

**Comment by felixhageloh** [comment]
great, I've added it!
