### ISSUE TITLE
New widget: UeberPlayer

### ISSUE THREAD

**Issue by aCluelessDanny** [felixhageloh/uebersicht-widgets#465]
Hiya there, this is a widget based off of [Playbox](http://tracesof.net/uebersicht-widgets/#Playbox). I ended up liking it a lot and updating it with things like adaptive colors and rewriting it to JSX.

Here ya go: https://github.com/aCluelessDanny/UeberPlayer

**Comment by felixhageloh** [comment]
very nice, thanks for sharing. I've finally added it
