### ISSUE TITLE
Wanted Widget: COVID19 Stats 

### ISSUE THREAD

**Issue by flow7** [felixhageloh/uebersicht-widgets#467]
Hi there,
sadly I don't know how to code, so it would take me forever, how to pull this together.
So, I'm looking for a widget, that display the most recent COVID19 case numbers on my display, for a country of my choosing, if possible.

Any suggestions, ideas, hints? Thanks a lot

**Comment by jhubig** [comment]
Hey,

something simple like that? The source is data from the John Hopkins University (US).
[covid.widget.zip](https://github.com/felixhageloh/uebersicht-widgets/files/4624639/covid.widget.zip)

Or here with the data from the Robert Koch Insitute (Germany).
[covid.widget_RKI.zip](https://github.com/felixhageloh/uebersicht-widgets/files/4624654/covid.widget_RKI.zip)

I'm also trying to write a widget where data is presented in a more readable way. But currently not enough time to finish it. Which data would be interesting for you?
This is what I have currently:

![image](https://user-images.githubusercontent.com/7255837/81865293-fa356a80-956d-11ea-9952-64907d8a7e5c.png)

Cheers,
Johannes

**Comment by flow7** [comment]
Wow, that is pretty awesome - yes, I was looking for something similar.
For example, these are my daily graphs I look at: OurWorldinData [Chart 1 day](https://ourworldindata.org/grapher/new-covid-cases-per-million?tab=chart&time=2020-04-24&country=IDN+THA+PHL+MYS) or the same data displayed over multiple days [here](https://ourworldindata.org/grapher/new-covid-cases-per-million?tab=chart&time=2020-04-05..2020-04-29&country=IDN+THA+PHL+MYS).

After installing your two widgets I got this screenshot:
![Screenshot 2020-05-14 at 15 54 53](https://user-images.githubusercontent.com/5027350/81908037-44186200-95fb-11ea-99fc-d390da0eb5d8.png)

It would of course be great if one was able to select the countries of preference.
Thanks for the effort!!

**Comment by jhubig** [comment]
Hey,

maybe the easiest and fastest way is to extract this zip file and use that as a basis:
[covid.js.zip](https://github.com/felixhageloh/uebersicht-widgets/files/4630764/covid.js.zip)

Then you select the graph/data you want on https://ourworldindata.org/. There you will always find the embed code. Copy the url (without the iframe):

![image](https://user-images.githubusercontent.com/7255837/81984068-90cc5f00-9634-11ea-8594-7a5073fe86b8.png)
![image](https://user-images.githubusercontent.com/7255837/81984198-c07b6700-9634-11ea-9c28-9a618f40fb06.png)

And this url you can paste in the widget file I attached above:

![image](https://user-images.githubusercontent.com/7255837/81984341-f6b8e680-9634-11ea-8255-14e59f7b3d24.png)

Done 😀

![image](https://user-images.githubusercontent.com/7255837/81984419-0afce380-9635-11ea-8011-5045b62d2d3d.png)

Hope this helps.

Cheers,
Johannes

**Comment by flow7** [comment]
Awesome -- I'll give that a try - thanks so much!
