### ISSUE TITLE
New widget: upcoming Exchange meetings

### ISSUE THREAD

**Issue by rtphokie** [felixhageloh/uebersicht-widgets#473]
Please add this widget to the gallery: https://github.com/rtphokie/ExchangeMeetings.widget

This widget fetches upcoming meetings from your Exchange calendar and displays them in a compact widget.  Includes brief information on the meeting, organizer and attendees.  Meetings with WebEx or Zoom links can be joined with a click and are indicated with WebEx and Zoom icons.

**Comment by felixhageloh** [comment]
thanks for sharing! I've added it
