### ISSUE TITLE
New widget: Authentic Weather [updated to use OpenWeatherMap API]

### ISSUE THREAD

**Issue by jeffzma2000** [felixhageloh/uebersicht-widgets#482]
Please add this widget to the gallery: https://github.com/jeffzma2000/authentic-ubersicht

**Comment by felixhageloh** [comment]
Hi thanks! This looks like it might be an update to an existing widget, in which case you don't have to re-submit. If it is a fork please let me know

**Comment by felixhageloh** [comment]
closing for now
