### ISSUE TITLE
Updated repo for SmoothAnalogClock widget

### ISSUE THREAD

**Issue by ruurd** [felixhageloh/uebersicht-widgets#483]
Hi Felix,

N00bySumairu transferred the repo for SmootAnalogClock widget to me. I proposed a small bugfix and it turns out he does not have a Mac anymore so he suggested to transfer the repo to me which I accepted. 

Can you please have a look at the latest changes and update to the latest version in master please?

Thanks,
Ruurd

**Comment by felixhageloh** [comment]
Hi, good to hear the widget has found a new owner! The widget gallery pulls the widget directly from GitHub, so update are automatically applied - you just have to make sure to update the widget.zip in the repo

**Comment by ruurd** [comment]
AFAIK that is what I did but somehow it seems to be stuck at a commit of 4 years ago.

**Comment by felixhageloh** [comment]
what's the repo URL?

**Comment by ruurd** [comment]
https://github.com/ruurd/SmoothAnalogClock.widget.git

**Comment by felixhageloh** [comment]
ah right, I see it is pointing to the previous repo still - let me see how I can fix this!

**Comment by felixhageloh** [comment]
alright i've updated the gallery. The widget now points to your new repo. Sorry I had assumed that you were using the same repo as before (but were the new owner)

**Comment by ruurd** [comment]
👍 Thanks Felix!
