### ISSUE TITLE
You have to add a readme

### ISSUE THREAD

**Issue by dp-IED** [felixhageloh/uebersicht-widgets#485]
I can take care of it if you want but you really can't expect people to read your code to figure out how to add tasks to a todo list widget.

**Comment by dp-IED** [comment]
this issue is specific to the to-do-list folder because it is appalling to propose such a widget without any instructions.

**Comment by felixhageloh** [comment]
Better to open an issue on the repo for the widget itself. I don't have access to the ToDo list widget's repo myself. The issue list here is only used to request new widgets being added to the gallery

Hope this helps
