### ISSUE TITLE
New Widget Premier League Table

### ISSUE THREAD

**Issue by EnglishLFC** [felixhageloh/uebersicht-widgets#488]
I had an old widget that no longer works, so I rewrote it completely.

The Github repository is here:
https://github.com/EnglishLFC/premier-league

**Comment by EnglishLFC** [comment]
The widget has been updated to make the competition configurable so that it can be used for a number of different leagues in Europe.

**Comment by felixhageloh** [comment]
hey, sorry for the late reply! If the repo is the same the widget should update automatically on the gallery (sometimes it takes a bit due to caching)
