### ISSUE TITLE
New widget: REALLY Simple Spotify Widget.

### ISSUE THREAD

**Issue by neutonfoo** [felixhageloh/uebersicht-widgets#490]
Please add this widget to the gallery: https://github.com/neutonfoo/Really-Simple-Spotify-Widget

Screenshot: 

<img width="1440" alt="screenshot2" src="https://user-images.githubusercontent.com/3114585/100548951-df35f980-3224-11eb-851b-f91c11a60e95.png">

**Comment by felixhageloh** [comment]
sorry this took a while. I've added this one as well!
