### ISSUE TITLE
New widget: Docker Box

### ISSUE THREAD

**Issue by neutonfoo** [felixhageloh/uebersicht-widgets#492]
Please add this widget to the gallery: https://github.com/neutonfoo/Docker-Box-Widget

Screenshot

<img width="258" alt="screenshot-1" src="https://user-images.githubusercontent.com/3114585/100548991-215f3b00-3225-11eb-9044-18bdcd15f378.png">

**Comment by felixhageloh** [comment]
thanks, I've added it!
