### ISSUE TITLE
New widget: ubersicht-widgets

### ISSUE THREAD

**Issue by zenopopovici** [felixhageloh/uebersicht-widgets#493]
Please add this widget to the gallery: https://github.com/zenopopovici/ubersicht-widgets/

**Comment by felixhageloh** [comment]
Hi thanks for sharing and sorry for the late reply! If I understand correctly this is a set of existing widgets. If so, then the gallery is not really the best place to host these kinds of sets. Please let me know if I am mistaken!

**Comment by zenopopovici** [comment]
It's OK. I will close it then. I could have created a single widget but people might want to disable / remove some of them.
