### ISSUE TITLE
New widget: Fetch

### ISSUE THREAD

**Issue by aleksilassila** [felixhageloh/uebersicht-widgets#494]
Fetchscript for übersicht, much like neofetch. [Repo](https://github.com/aleksilassila/uebersicht-fetch)

<img width="516" alt="Screenshot 2020-12-16 at 14 47 45" src="https://user-images.githubusercontent.com/25369243/102351376-03c4fc00-3faf-11eb-830b-2f7684e8ae2f.png">

**Comment by felixhageloh** [comment]
Thanks, I've added it!
