### ISSUE TITLE
New widget: calendar

### ISSUE THREAD

**Issue by knazarov** [felixhageloh/uebersicht-widgets#497]
Please add this widget to the gallery: https://github.com/knazarov/ubersicht-calendar

This widget shows a calendar in a sidebar pretty much like the traditional Apple calendar.

**Comment by felixhageloh** [comment]
Hi thanks for sharing! I hit an issue when trying to add your widget: there is already another widget with the same ID. I'm using the repo name as ID (ubesicht-calendar in this case) and so far it has worked out fine. 
This shows I probably need to think of a different ID generation scheme, but I can't promise any ETA on that. For now, the quickest way to get this widget added is probably picking a different repo name if possible. 

Let me know what you prefer and sorry for the hold up

**Comment by knazarov** [comment]
Hi, I've renamed the widget to https://github.com/knazarov/ubersicht-calendar-widget

**Comment by knazarov** [comment]
By the way, calendar entries are now clickable, with support for parsing Zoom URLs. If you click on a meeting with a Zoom URL in it, it will follow the link.

**Comment by felixhageloh** [comment]
very nice 👍! I've added it

**Comment by knazarov** [comment]
The GitHub link on the widget page is broken. It says `ttps://github.com/knazarov/ubersicht-calendar-widget` (missing initial "h")

**Comment by felixhageloh** [comment]
sorry about that, fixed!
