### ISSUE TITLE
New widget: Persona_5_Theme_Calendar

### ISSUE THREAD

**Issue by darkjuanjo** [felixhageloh/uebersicht-widgets#505]
Please add this widget to the gallery: https://github.com/darkjuanjo/Persona_5_Calendar
Fixed the issues I thought prevented this widget from being added.

**Comment by felixhageloh** [comment]
thanks for sharing, I've added it!

**Comment by darkjuanjo** [comment]
Awesome Thanks!
@felixhageloh  is it possible to change the displayed name to Persona_5_Calendar instead of Persona_5_Theme? Also I don't know if this is a bug or if I need to fix my code but when when I edit the jsx files and save it and the widget reloads, the timers in the code start adding up. Is there a way to fix this?

**Comment by felixhageloh** [comment]
hi, if you update the name inside the manifest file I can update it!

**Comment by darkjuanjo** [comment]
Awesome thanks! I've updated the JSON file.

**Comment by felixhageloh** [comment]
The gallery is updated as well! (you might have to clear cache to see the change)

**Comment by darkjuanjo** [comment]
@felixhageloh  Thank you :D
