### ISSUE TITLE
New Widget: Monit

### ISSUE THREAD

**Issue by atika** [felixhageloh/uebersicht-widgets#510]
Hi. Just released a new widget written with React to display the status of monitored services with [monit](https://mmonit.com/monit/) of multiple instances.

https://github.com/atika/Ubersicht-Monit

Just a few question If you can help me:

* Can I modify the `previousState` object to update only a part of it?
* Can I reload the widget without AppleScript (tell the widget to refresh and execute the command immediately)?

It's the first time I used React, some examples in the Readme confused me at the beginning (see below), but I managed to make it to work.

```js
 dispatch({ type: 'FETCH_SUCCEDED', data: response.json() });
```
`updateState` receive a promise with `response.json`

**Comment by atika** [comment]
Could you add the widget to the gallery ?

**Comment by felixhageloh** [comment]
Sorry about this, I noticed I had broken my GitHub notifications for these and am just clearing out old requests! I've finally added it
