### ISSUE TITLE
Webkit-filter render is terrible

### ISSUE THREAD

**Issue by Froxcey** [felixhageloh/uebersicht-widgets#526]
I don't know if it's problem with my own widget, webkit, or uebersicht. I created a widget, and I added blur gradient to enhance the esthetic and it looks good. However, the blur randomly disappear and reappear. Also, the rendering has a huge delay. I tried to optimize my code, but no hope.

**Comment by felixhageloh** [comment]
I have not found a workaround for this this yet unfortunately
