### ISSUE TITLE
NASA APOD widget (redone)

### ISSUE THREAD

**Issue by KiwiSkunk** [felixhageloh/uebersicht-widgets#527]
https://github.com/KiwiSkunk/APOD

Rewrite and improvements to my old widget

**Comment by felixhageloh** [comment]
Thanks, I've added it!  Do want the old widget removed? If so, can you provide the name?

**Comment by KiwiSkunk** [comment]
Hi Felix
Yes please. apod-view.widget.
Cheers

Sent while mobile...

**Comment by felixhageloh** [comment]
done!

**Comment by KiwiSkunk** [comment]
Hi Felix,

Despite all my testing (3 months) I have been told of an issue which I fixed today. 
There is a new zip file on GitHub. GitHub.com/kiwiskunk/apod

Really sorry about this. I thought testing was complete. 


Sent while mobile...

**Comment by felixhageloh** [comment]
No worries, that's the reality of building software! 
If you updated the zip file in your repo, the widget gallery should automatically point to the new version (could be that it is cached for a bit tho). Let me know if that's not the case!

**Comment by KiwiSkunk** [comment]
Thanks Felix. Zip is updated so I’ll check in a few days. 
Time to start on the next widget…

Sent while mobile...
