### ISSUE TITLE
New widget: Aerial for Übersicht

### ISSUE THREAD

**Issue by aleksilassila** [felixhageloh/uebersicht-widgets#533]
Please add this widget to the gallery: https://github.com/aleksilassila/uebersicht-aerial

**Comment by felixhageloh** [comment]
Hi thanks for sharing! I noticed that this is using Apple TV screensavers, so I am wondering if this is public data?

**Comment by aleksilassila** [comment]
Hey! The widget fetches a list of video urls for the wallpapers from this site https://bzamayo.com/watch-all-the-apple-tv-aerial-video-screensavers. The video URLs point to the publicly available videos on apples servers, so I assume it's okay to stream them. So no authentication required, anyone can download them from Apple.

**Comment by felixhageloh** [comment]
sorry for delay! Thanks for clarifying - I've added it!
