### ISSUE TITLE
CSP blocks firebase resource loading

### ISSUE THREAD

**Issue by 0x41c** [felixhageloh/uebersicht-widgets#534]
Due to the restrictive CSP, the firebase resource is unable to load on the widget download page. Adding `https://www.gstatic.com` to the CSP would fix this issue.

**Comment by 0x41c** [comment]
I just saw recent commit history. I think a better fix to go with what you're doing would be to completely remove the firebase load from the source.

**Comment by felixhageloh** [comment]
thanks! Yeah unfortunately someone corrupted the downloads data to make a point. It was a bit of a rushed change so I overlooked this place where firebase was still loaded
