### ISSUE TITLE
Update widget: waifu

### ISSUE THREAD

**Issue by Hurray0** [felixhageloh/uebersicht-widgets#535]
Please add this widget to the gallery: https://github.com/Hurray0/uebersicht-live2d

Sorry but I need to update the widget, because there is a file name error for user to use

**Comment by felixhageloh** [comment]
if this widget is already on the gallery then you just need update your repo (and the zip file) and changes will automatically be applied. There is some caching, so sometimes it can take a while till you see the updated

**Comment by Hurray0** [comment]
done
