### ISSUE TITLE
New widget: Simple calendar

### ISSUE THREAD

**Issue by romanhaa** [felixhageloh/uebersicht-widgets#550]
Please add this widget to the gallery: https://github.com/romanhaa/ubersicht-calendar-widget

**Comment by felixhageloh** [comment]
Hi thanks for sharing! There is a current limitation that widget names need to be unique and the name `ubersicht-calendar-widget` is already taken. Could you re-submit it with a different name? Sorry for the hassle

**Comment by romanhaa** [comment]
Done; see https://github.com/felixhageloh/uebersicht-widgets/issues/552
