### ISSUE TITLE
New Widget: BinanceCryptoPrices

### ISSUE THREAD

**Issue by AtesDANIS** [felixhageloh/uebersicht-widgets#571]
Please add this widget to the gallery: https://github.com/AtesDANIS/uebersicht-BinanceCryptoPrices

**Comment by felixhageloh** [comment]
Hi, thanks for sharing! Can you run your repo through the 'submit widget' workflow again (at https://tracesof.net/uebersicht-widgets/). It currently fails validation

**Comment by AtesDANIS** [comment]
thanks for info, I just did it.

**Comment by felixhageloh** [comment]
great, it passed now. Added it!
