### ISSUE TITLE
New widget: 八字预测 The Eight Char Prediction

### ISSUE THREAD

**Issue by tly1378** [felixhageloh/uebersicht-widgets#589]
Ancient Chinese traditional divination, Bazi prediction desktop widget.

**Comment by tly1378** [comment]
Please add this widget to the gallery: https://github.com/tly1378/widgets

**Comment by felixhageloh** [comment]
hey thanks for sharing! Can you use a repo name that matches the name of your widget? Right now the repo name is used as an widget ID, so the ID of your widget will be `widgets` which is probably not what you want :)

You can open a new issue once you have changed the name. Thanks again!
