### ISSUE TITLE
Neofetch Display

### ISSUE THREAD

**Issue by hw2007** [felixhageloh/uebersicht-widgets#597]
Made a widget to display neofetch stats on your desktop. Here it is!!
https://github.com/hw2007/ubersicht-neofetch

![img](https://github.com/user-attachments/assets/8182c43e-1756-49fe-820e-3334b72bfad9)

**Comment by felixhageloh** [comment]
sorry for the very late reply. Great looking widget, I've added it!

**Comment by hw2007** [comment]
> sorry for the very late reply. Great looking widget, I've added it!

Awesome thanks!! No worries about the late reply :)
