### ISSUE TITLE
NASA Astronomy Picture of the Day

### ISSUE THREAD

**Issue by hw2007** [felixhageloh/uebersicht-widgets#598]
Made a neat widget to show NASA's Astronomy Picture of the Day on your desktop.
https://github.com/hw2007/ubersicht-nasa-image/

![SCR-20241012-taio](https://github.com/user-attachments/assets/d0ed7192-47cd-4bf6-a46d-6cac8817dfd5)

**Comment by felixhageloh** [comment]
I've added it! Again, sorry for the late reply
