### ISSUE TITLE
System Stats Set

### ISSUE THREAD

**Issue by jasonshanks** [felixhageloh/uebersicht-widgets#65]
I hope you don't mind my retooling your own widgets UI?

Maybe a separate section or tag for sets in the future.

https://github.com/plmtr/Ubersicht-System-Stats-Set

**Comment by Baxter900** [comment]
Imma chime in here and say that I think a preset setup section would be nice. I currently have a bunch of rethemed widgets packaged with my animated backgrounds widget (though there are other reasons why, mainly to demonstrate how you would integrate other widgets such that they float, and have layers also), but it would be nice if I could place those in a separate area and slim down the size of the main file, then reference to that for the people who either want to re-theme widgets themselves and want examples, or who just want a nice, pre-made set.

**Comment by Porco-Rosso** [comment]
I think sets should for sure be a different section.

**Comment by felixhageloh** [comment]
I have not had many more people trying to share sets, so I am closing this for now
