### ISSUE TITLE
Spotify Script not working in Yosemite?

### ISSUE THREAD

**Issue by mainderay** [felixhageloh/uebersicht-widgets#95]
I get this error when I start Spotify in Yosemite:

2014-10-29 13:51:53.812 osascript[82267:5160560] Error loading /Users/raymond/Library/ScriptingAdditions/List &amp; Record Tools.osax/Contents/MacOS/List &amp; Record Tools:  dlopen(/Users/raymond/Library/ScriptingAdditions/List &amp; Record Tools.osax/Contents/MacOS/List &amp; Record Tools, 262): no suitable image found.  Did find:
	/Users/raymond/Library/ScriptingAdditions/List &amp; Record Tools.osax/Contents/MacOS/List &amp; Record Tools: no matching architecture in universal wrapper
osascript: OpenScripting.framework - scripting addition "/Users/raymond/Library/ScriptingAdditions/List &amp; Record Tools.osax" declares no loadable handlers.

I did verify that "List & Recording Tools.osax" does indeed exist in the directory specified above. Any ideas? Let me know how I can help. Thank you!

-raymond

**Comment by castlesinthesky** [comment]
mainderay, did you ever figure out the problem? I am trying to run this widget but just keep running into this error display: "59:64: syntax error: Expected end of line but found identifier. (-2741)" soberstadt - any thoughts? thanks!

**Comment by soberstadt** [comment]
Yeah, that's a good question, should this issue be closed? The syntax error sounds like it would be an issue with the files, maybe try re-downloading the files and restarting uebersicht. This is concerning the https://github.com/felixhageloh/uebersicht-widgets/tree/master/Spotify-Current-Track widget right?

**Comment by castlesinthesky** [comment]
soberstadt - that's correct. I've tried to re-download and restart; not sure why I keep running into the problem as it seems other people are not necessarily having this issue. Stupid MBP! :)

**Comment by soberstadt** [comment]
Huh, well if that's not the problem, I'm lost. @felixhageloh do you have more tips on debugging this?

**Comment by felixhageloh** [comment]
hmm I didn't quite follow this. Sounds like it is two different issues - are we talking about the last one (the syntax error)?

**Comment by soberstadt** [comment]
I think the original issue was resolved. But I don't know how to help castle with their syntax error.

**Comment by felixhageloh** [comment]
Ah ok, in that case I think it's best to check if the command itself runs and see the output or errors it gives. @castleinthesky could you try to run the widget command in the terminal and share the output here? 
Let us know if you have questions on how to do that!

**Comment by cah242** [comment]
I'm having the same issue as @castlesinthesky 

The widget has been working great for months, and I haven't touched the file since I first installed it and moved it to the bottom left of the screen. Now I'm getting that error just in the last few days. I can try @felixhageloh's suggestion, but I don't know how to do it.

Thanks.

**Comment by soberstadt** [comment]
I'm actually thinking that this is a Spotify bug. I'm seeing no AppleScript commands working for me.

I'm looking into it further.

**Comment by soberstadt** [comment]
I guess we're stuck waiting...
https://twitter.com/SpotifyPlatform/status/575615437813202944

**Comment by cah242** [comment]
Good to know. Thanks!

**Comment by soberstadt** [comment]
Looks like this is working now on Spotify 1.0.3.101 You good with closing this?

**Comment by cah242** [comment]
Yep, perfect. Thanks!

--
Chad Harrison




On Thu, Apr 9, 2015 at 9:28 AM -0700, "Spencer Oberstadt" <notifications@github.com> wrote:












Looks like this is working now on Spotify 1.0.3.101 You good with closing this?
